### ISSUE TITLE
Intercepting flags set by USPAPI (i.e., non-cookie IAB US Privacy Strings) in iFrames

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#148]
One important point is that there are sites that are not actually modifying the USPAPI cookie in connection with GPC being enabled or disabled. Instead of reading the cookie value directly, they call into the IAB USP API to get the consent string. They use a wrapper `__uspapi(‘getUSPData’, 1, (data) => console.log(data))`. If GPC is enabled, then it will override the cookie value with `Y` in the third position for "no consent." If I understand correctly, this is what is happening on wordpress.com and longreads.com.

So, the question is whether that can be actually observed in HTTP requests or whether other approaches are needed. A starting point for looking into this issue is to examine wordpress.com and longreads.com.

**Comment by SebastianZimmeck** [comment]
Here is the [IAB framework](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/USP%20API.md).

**Comment by SebastianZimmeck** [comment]
Maybe, it is also worthwhile to set up a word press blog ourselves. Would we have this functionality?

**Comment by SebastianZimmeck** [comment]
I will ask for some more information, and maybe there are some example sites as well.

**Comment by SebastianZimmeck** [comment]
Based on our discussion today, there may not be a whole lot that we can do here. Broadly, I can think of that we are detecting whether `__uspapi` JS code is sent to the browser to run there (and for that detection we may actually need Mozilla's [webRequest.filterResponseData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData) API; in that sense the whole Chrome/Firefox debate plays a role here). However, detecting the code does not tell us whether that code actually _was_ run. To make that determination, we would need to look for the US Privacy String (e.g., `1YYN`) in the remaining web traffic of the browser with that site. Maybe, that is easily doable, maybe not.

For the time being, we are leaving this issue and revisit.

**Comment by SebastianZimmeck** [comment]
As @dharb found:

> In Wordpress's case, they've modified this function [that is, the __uspapi function] to override the value of the US Privacy String if a GPC signal is present--which is why you'll see that the usprivacy cookie is 1YNN, but __uspapi('getUSPData', 1, (data) => console.log(data)) returns 1YYN on sites like https://adtechmadness.wordpress.com/2021/02/18/all-your-are-belong-to-me/.

So, basically, we still have the cookies; just it may not be updated after the site receives the GPC signal, which makes it tricky to detect whether the site is reacting to GPC. @kalicki1 is looking into this right now ...

**Comment by SebastianZimmeck** [comment]
OK, I tested this. For me, the cookie was actually updated after opting out; from 1YNN to 1YYN. I clicked on the Do Not Sell link at the bottom (without accepting cookies actually), which linked me to another page, from which I opted out. Not sure if they fixed their implementation or if there is a difference because I am in California.

<img width="1241" alt="Screen Shot 2021-09-05 at 7 00 19 PM" src="https://user-images.githubusercontent.com/11034003/132151054-370b67eb-252e-4a51-88c8-b3e7060796bd.png">

The USPAPI situation was that I could find both 1YNN (line 1008) and 1YYN (line 989) in the code. But it looks like this is just hardcoded and not actual values being passed around. The cookie value stayed 1YYN throughout. 

<img width="1317" alt="Screen Shot 2021-09-05 at 7 05 14 PM" src="https://user-images.githubusercontent.com/11034003/132151096-9c0ba64b-6f81-4b1f-9b11-f45ef5935380.png">

<img width="1318" alt="Screen Shot 2021-09-05 at 7 08 14 PM" src="https://user-images.githubusercontent.com/11034003/132151132-8d631890-8a5e-420e-b4d9-15a30eada13a.png">

**Comment by kalicki1** [comment]
I have been working on implementing this so that a visit to a site in analysis mode will automatically register a `__uspapi()` call when the window finishes loading via a `window.onload` call. So far I have made the connection necessary between the injected `__uspapi()` call and the background script via the content script, which is the bulk of the work. What remains is the following:

- [ ] Make sure it only runs in `analysis` mode (never in protection)
- [ ] Save the incoming data via a processor function in the analysis background script
- [ ] Manually skim the `__uspapi()` implementation code as is accessible as a client to see what is being done

**Comment by SebastianZimmeck** [comment]
Different from what we initially thought, there might be actually no difference between the US Privacy String value in the cookie of a website and the value it processes in the `__uspapi` (if it uses that). Thus, this issue seems less critical now, and @kalicki1 aims to finish it over the next few days.

**Comment by kalicki1** [comment]
Here are some notes we found today from a few years ago regarding early `uspapi()` implementation details that may be useful down the line: https://github.com/prebid/Prebid.js/issues/4425

**Comment by SebastianZimmeck** [comment]
We do not quite understand how the US Privacy String works for iFrames. We may need to reach out to the IAB. But before we do that @kalicki1 will look a little bit more into the documentation and try to make sense of it.

**Comment by SebastianZimmeck** [comment]
This is a finer point of the analysis and we should get the connection frontend-backend and analysis functionality in general get done first before addressing this issue.

**Comment by SebastianZimmeck** [comment]
Per our discussion today, this seems basically done. @kalicki1, please close once completely done.

**Comment by kalicki1** [comment]
I have read up a little more on the IAB documentation related to this issue and I think I agree that this issue is basically done. I will go ahead and close it (if we ever need it we can reopen it).
