### ISSUE TITLE
Switch to mv3

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#175]
It seems like updating our manifest version to V3 might solve a couple different issues with one stone. @chunyuema mentioned to me earlier that it might be the case that updating to V3 will resolve some memory management issues mentioned in issue #164. 

In addition, I believe that Chrome may be depreciating the tabs.executeScript call I use to execute handling the GPC DOM property (issue #174). It seems that it's being replaced with [scripting.executeScript](https://developer.chrome.com/docs/extensions/reference/scripting/), which may be why the DOM functionality is broken after refactoring. This needs more research however, my findings are surface level for the time being. 

This isn't urgent, we can address it after the code base is all set.

**Comment by kalicki1** [comment]
Mentioning @stanleymarkman and @kbeliauski so you all can keep up with changes here.

**Comment by SebastianZimmeck** [comment]
As a note for the future: in a [blog post](https://blog.chromium.org/2019/06/web-request-and-declarative-net-request.html) Google announced the [replacement of the Web Request API with the Declarative Net Request API](https://blog.chromium.org/2019/06/web-request-and-declarative-net-request.html) for Manifest V3 – the next version of the Chrome Extensions platform. This change also affects our use of the Web Request API.

As Google explains, with the Web Request API requests are send indiscriminately to an extension, and the extension filters out what it needs. With the Declarative Net Request API, "[i]nstead of Chrome sending all the information about a request to the listening extensions at the time of the request, extensions register rules that tell Chrome what to do if certain types of requests are seen." Maybe, we can declare most/the requests we need. "The Declarative Net Request API now allows for the registration and removal of dynamic rules - specified at runtime rather than statically in the manifest. We’ve also added the capability to remove common tracking headers, such as Referer, Cookie, and Set-Cookie."

**Comment by SebastianZimmeck** [comment]
One good point that @stanleymarkman brought up is that we can develop new code already with an eye on compatibility with V3. That way, we avoid refactoring in the future.

**Comment by stanleymarkman** [comment]
Tried to switch our project to v3 and got many issues on firefox- turns out, Mozilla isn't supporting v3 yet at all, with developer testing planned for "q4 2021" (https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/)
Mozilla is having pretty open discussions on Bugzilla and the forums about v3- we could even try making suggestions there to preserve our precious APIs.

**Comment by SebastianZimmeck** [comment]
I am re-opening this issue as we probably have to address it sooner or later. Current Chrome extensions with Manifest V2 will [stop running](https://developer.chrome.com/blog/mv2-transition/) on Chromium in January 2023.

**Comment by SebastianZimmeck** [comment]
@chunyuema and @ekuller have done some great migration work on our GPC Privacy Choice extension (gpc-privacy-choice [issue-168](https://github.com/privacy-tech-lab/gpc-privacy-choice/issues/168) and related [PR](https://github.com/privacy-tech-lab/gpc-privacy-choice/pull/169)), on which they can also advise in the context of OptMeowt.

**Comment by SebastianZimmeck** [comment]
We should address the migration of OptMeowt to v3 within the next weeks.

**Comment by OliverWang13** [comment]
Commenting to help me keep track of what has been done:

- Changed "manifest_version" to 3

- Changed `chrome.tabs.executeScript` to `chrome.scripting.executeScript` (Comment: does more work need to be done here? I will test in the future. Seems like scripting... takes a file and a target)

- Currently looking into background service workers

**Comment by OliverWang13** [comment]
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/

https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/

**Comment by SebastianZimmeck** [comment]
> Changed "manifest_version" to 3

Not sure, if you make individual changes like this, I could imagine the extension breaks. Ultimately, we are probably looking at a pretty fundamental refactoring and rewriting here.

(cc'ing @chunyuema, @ekuller, and @bella-tassone to counsel)

**Comment by OliverWang13** [comment]
Yes, individual changes like that will break it, I am just working through slowly and recording what I do here for my memory.

**Comment by kalicki1** [comment]
@OliverWang13 and I are going through some of the [Migrating to MV3 docs](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#host-permissions) and changing up the codebase accordingly. Here are some outstanding to-do tasks: 

### `manifest.json`: Review `host_permissions`
- For the time being, we are setting these to both `*://*/*` and `<all_urls>` although it seems support for `<all_urls>` is being dropped? Let's go back to this and review if something breaks.
- We might also have to remove `<all_urls>` as the Chrome web store might reject extensions with it? Or also extensions without `host_permssions`.

### Update Webpack `eval-source-map` for Dev build if evals are NOT allowed in CSPs anymore

**Comment by kalicki1** [comment]
Related GitHub issue: 

[What to do about Manifest V3 #666](https://github.com/ipfs/ipfs-companion/issues/666)

**Comment by kalicki1** [comment]
The way I see this now is that we have 3 big priority tasks to resolve here first: 

- [ ] Update the `manifest.json` properly so we can debug the rest of the MV3 changes
- [ ] Refactor all of the necessary APIs to their MV3 counterparts (see comment with outline at the top of issue)

**Comment by SebastianZimmeck** [comment]
> Refactor all of the necessary APIs to their MV3 counterparts

This is likely a very hard nut to crack. The Privacy Choice team is currently working on that, and the API replacement is very difficult. The new API behaves very unpredictably. On some sites you can inject the GPC headers and on others not. Maybe, again a site issue (a la CSP).

**Comment by kalicki1** [comment]
I just pushed a change to our `manifest.json`'s. 

- Removed `web_accessible_resources` key (we only used it to read JSONs, which we no longer do)
- Updated `content_security_policy` key as appropriate for MV3. 
- Updated Webpack config [`devTool` option for development] (`unsafe-eval`'s are no long allowed)

As we can no longer use `unsafe-evals`'s at any point during development it seems, I changed our developement `devTool` Webpack config option to use a `cheap-source-map` instead of an `eval-source-map` which now throws errors on install. If this poses issues in the future we can change it (e.g., if it is too slow; if it uses inline JS which is not allowed, etc.)

**Comment by SebastianZimmeck** [comment]
Great!

>  it does in fact work in most places

Does it work on *all* sites? That was one problem that @chunyuema, @ekuller, and @bella-tassone also encountered. The injection of the GPC header did not work on some sites, and it was unclear why.

**Comment by kalicki1** [comment]
@SebastianZimmeck I ran a quick trial on the 16 sites below and **only** the Chrome Web Store link (of the sites with request headers attached) didn't have a DNT nor a GPC signal attached. I'm not sure if this is related to the fact it is a chrome subdomain and as a result is ignored by the declarativeNetRequest API, but it might be something to look into. 

In terms of the API issue the other team has, are there example sites that consistently don't work or is the issue that declarativeNetRequest doesn't work consistently even across the same sites? 

Not sure if it is worthwhile to note but an amazon internal redirect didn't reattach our added request headers, though the main page with a 200 status code did have the signals. 

- `globalprivacycontrol.org`
- `global-privacy-control.glitch.me`
- `nytimes.com`
- `youtube.com`
- `newyorker.com`
- `ebay.com`
- `example.com`
- `javascript.info`
- `epicgames.com`
- `google.com`
- `chrome.google.com` (web store link)
- `microsoftedge.microsoft.com` (edge store link)
- `apple.com`
- `duck.com`
- `hulu.com`
- `wesleyan.edu`

**Comment by SebastianZimmeck** [comment]
>  In terms of the API issue the other team has, are there example sites that consistently don't work or is the issue that declarativeNetRequest doesn't work consistently even across the same sites?

@chunyuema, @ekuller, and @bella-tassone, do you happen to have an example?

**Comment by kalicki1** [comment]
After our meeting today with the GPC Privacy Choice group, @OliverWang13 and I decided on a few general tasks that we can split up to handle the migration to a system using the declarativeNetRequest API.

1. Check if we can continue to **dynamically populate our domainlist** as users browse the web (can we use webRequest/webNavigation reliably w/o a persistent service worker?). This can affect our UI; will we have to migrate to a text-based input scheme for domainlist exceptions? 
2. **Implement the DNR dynamic rules.** Create an API wrapper around the DNR calls that will (1) add the rule to an IDB store, then (2) add the rule to the DNR rules list 
3. **Move away from using global variables** to a non-persistent mode of storing "cached" data (i.e., get rid of them)

**Comment by kalicki1** [comment]
I pushed a small change that lets us add and remove dynamic declarativeNetRequest rules that exclude added domains from receiving GPC and DNT signals, overriding our universal "send GPC" rule. It seems to be working well from my limited trial . What's left (point 2 from the above comment) is to reconnect this to localstorage or an IDB store.

**Comment by SebastianZimmeck** [comment]
As discussed, we are going to try to finalize the switch to v3 within two weeks.

**Comment by kalicki1** [comment]
I pushed a change that connects the new backend domainlist API I made to the frontend. It works for the most part—the only outstanding issue on this is that the 3rd-party toggles generated in the popup connect to the 1st party domain for some reason. This can be sorted out at another time or when testing the whole extension.

**Comment by SebastianZimmeck** [comment]
> the only outstanding issue on this is that the 3rd-party toggles generated in the popup connect to the 1st party domain for some reason. This can be sorted out at another time or when testing the whole extension.

OK, feel free to open an issue or keep track of it in another way.

**Comment by SebastianZimmeck** [comment]
The only other open issue on mv3 is #259, and then we should be done.

**Comment by SebastianZimmeck** [comment]
We keep this issue open, but there is nothing concretely here to do. Every work item is covered by the individual mv3 issues.

**Comment by SebastianZimmeck** [comment]
@kalicki1 merged the MV3 branch into main. So, closing this!
