### ISSUE TITLE
Implement functionality for identifying Do Not Sell links

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#194]
For our compliance analysis we need to identify Do Not Sell links on homepages. That way we know that a visited site is subject to the California Consumer Privacy Act (CCPA). In principle, this task is easy. I can see two issues, though: first, if the link is dynamically loaded via JavaScript, we may not see it; second, the link text may have different variations ("Do Not Sell my Info", "Do Not Sell my Data". etc., maybe use regular expressions?).

This issue is similar to the closed issue #149 with the difference that we can assume that the user will be on the homepage of the site to analyze, i.e., we do not need to find a way to navigate to the homepage if that is not the case. If a user is on a non-homepage site, we simply do not analyze.

For the time being I am assigning all of us. We can figure out who does it once we get to implementing the analysis functionality.

At some point Daniel implemented a [crawler to identify such links](https://github.com/privacy-tech-lab/gpc-analysis). Whoever works on this may find inspiration there (for the identification; not for the crawling, which we do not need).

**Comment by SebastianZimmeck** [comment]
Identifying Do Not Sell links is also a good first issue (just as #183; we can discuss next week @OliverWang13).

**Comment by SebastianZimmeck** [comment]
There are two steps of approaching this:
1. How to identify links on the homepage
2. How to integrate the link identification functionality into the current codebase

**Comment by SebastianZimmeck** [comment]
This should be written in JavaScript because it should be part of our extension

**Comment by OliverWang13** [comment]
For dealing with multiple phrasings for different Do Not Sell links, I made an array called phrasings that every text object is compared against. Currently, I have the code getting every element on the page, which may be inefficient but I will test to see whether all Do Not Sell links are using the same tag (maybe <a>). A small issue with the current implementation is that if the page happens to have random text about Do Not Sell, it will mark those as found (this may be fixed by searching by <a> tag only).

**Comment by SebastianZimmeck** [comment]
> I have the code getting every element on the page, which may be inefficient ... if the page happens to have random text about Do Not Sell

Good progress, @OliverWang13. We know that links are almost certainly in the footer of a page. Can you leverage that in some way? That may improve both efficiency and avoidance of random text.

**Comment by OliverWang13** [comment]
Links have generally been in the footer, but I have found them in some other places a couple of times. Having looked at around 20 sites, the link is usually an <a> tag but was once a <button>. Perhaps I could just search by those instead.

**Comment by SebastianZimmeck** [comment]
> Perhaps I could just search by those instead.

Yes, try to find a good proxy so that ideally we have no false negatives (missed Do Not Sell links) and as few false positives (items classified as Do Not Sell links that shouldn't have been classified as such) as possible.

**Comment by OliverWang13** [comment]
> tag but was once a

Sorry, this line read as an 'a' tag and a 'button' tag, but Github had weird interactions with the greater than less than symbols.

**Comment by SebastianZimmeck** [comment]
You can use `a` in markdown here if you want to write code (i.e., the following symbols `).

**Comment by OliverWang13** [comment]
Here is a link to the spreadsheet where I have been recording the tests: https://docs.google.com/spreadsheets/d/19Wi2PaPsEOfiSdeaOEdSNg5QCzJbRmc7f5rHhXYzO6E/edit#gid=0

**Comment by SebastianZimmeck** [comment]
As discussed yesterday, @OliverWang13 will provide current performance results. Then, once we are clear about the code structure for the analysis mode, we will bring the link analysis functionality into main.

**Comment by OliverWang13** [comment]
Now that it is refactored, I will likely have to test it with the sites that I found that have the DNS links. There are still a couple of sites that are not working perfectly although I am not sure why. Anyone should feel free to check out the Sheets and take a peek at the websites that are not functioning. Do not hesitate to give feedback on the RegExp that I implemented.

**Comment by OliverWang13** [comment]
Additionally, I have not found a way to make sure that the site we are on is a homepage.

**Comment by SebastianZimmeck** [comment]
One way would be to check that there is nothing after the top level domain, e.g., nothing after `.com`, `.co.uk`, `de`, etc. But it is not necessary if it is difficult. We just have to tell users that the analysis mode will only work on homepages.

**Comment by OliverWang13** [comment]
I have updated the links spreadsheet, and the link finder works on most sites present (some sites do not contain the link and are included to find possible false positives). If more sites that did not contain the link were present I am confident we would have a much smaller percentage of sites that it does not work on.

**Comment by SebastianZimmeck** [comment]
Great, thanks, @OliverWang13! Could you give some concrete numbers or percentages?

**Comment by OliverWang13** [comment]
Yes, there are 60/66 (~91%) unique links working as of now. As I find more sites with the link I can add them and I expect our percentage of working links would rise, as most sites follow conventions that we can find.

**Comment by SebastianZimmeck** [comment]
I think that is sufficient for the time being. We have to do a systematic testing later on. But for now it is fine to bring in the changes to the main branch once @kalicki1 gives the green light.
