### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#198]
This is a reminder to update the Wiki once we have pushed our release since we have had a few major updates to the codebase that might have fixed issues noted there.

**Comment by kalicki1** [comment]
Small note: I mentioned issue #192, regarding 3rd party domains shown in the popup, on a new developer explanations page on the wiki.

**Comment by SebastianZimmeck** [comment]
Can you update the Wiki, @kalicki1 (if there is something to update)?

**Comment by kalicki1** [comment]
Less ended up being changed than I anticipated. I pushed a small change to our explanation regarding what happens when OptMeowt forces a sign-out upon turning off Do Not Sell on a particular site. 

I will go ahead and close this issue for issue #197.
