### ISSUE TITLE
Fix header signal not sent in Chrome

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#200]
I was doing some last minute testing on both Chrome and Firefox for versioning issues with our new release and happened to notice that our Chrome version does not actually properly set our GPC header signals on the [GPC test server](https://global-privacy-control.glitch.me/). I took a cursory look at the code and think [this line](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/c4a0a74a12d358d02711a53eb8f5ebdb2ed41a72/src/background/events.js#L47) in `events.js` is the issue. 

I believe that the asynchronous callback on our `webRequest.onBeforeSendHeaders` call gets skipped when the listener is supposed to be blocking in Chrome exactly because it is async. This Chrome behavior makes sense to me, but it makes me wonder why it works in Firefox the first place. 

I think a quick fix might be just to cache the whole domainlist in the background and make it mirror our local database after the fact. I will look into this.

**Comment by kalicki1** [comment]
I just pushed a patch that should fix this problem. 

I think the reason for the issue is, as I mentioned, Firefox for some reason waits for the async callback to finish running on our blocking `webRequest.onBeforeSendHeaders` call, while Chrome does not. I couldn't figure out for certain.

Since this was the case, I simply added a `domainlist` and a `mode` cache to `events.js` that should always mirror what happens in our indexedDB database. Changes to the cache should always be pushed asynchronously to the database after the fact.

**Comment by kalicki1** [comment]
I will need to create a small additional update to ensure that changes to the database are pushed to the cache.

**Comment by SebastianZimmeck** [comment]
It seems that for Chrome it is not working yet. I visited citi.com and amazon.com, and for both sites I did not see the GPC request header. I had GPC enabled for all domains. I built from source and using the most recent Chrome version. I can also confirm that it works for Firefox.

**Comment by kalicki1** [comment]
Good catch @SebastianZimmeck! I took a look at my code and realized in the commotion I forgot to remove the original offending `async` keyword haha, everything else that was implemented seems good. I just pushed that patch.

**Comment by SebastianZimmeck** [comment]
Great! I can confirm, that fixed it, @kalicki1!

**Comment by kalicki1** [comment]
I'm reopening this because I never pushed an update to ensure that the domainlist in our background page cache was properly synced with the domainlist in the longterm database. 

I'm currently working on implementing a `syncDomainlists()` function that simply iterates through the domainlist in indexedDB and adds domains that don't exist in the cached domainlist to it, and vice versa, i.e., iterate through the cached domainlist and check for domains that don't exist in indexedDB and make sure to push them. 

In order for this to not interfere with normal operation, I'm using `chrome.runtime.connect` to create longterm ports between the popup and the options page. Then I'm listening for when the ports are closed, i.e. when the pages are closed and hence users are done with their changes, to run `syncDomainlists()` from the background page. Checking the logic by hand, this function should be okay. I will push the changes shortly.

**Comment by kalicki1** [comment]
I have not tested the new sync function extensively, but the changes have been pushed.

Just to not what has been changed, I added `syncDomainlists()` to `events.js`, as well as a port listeners in `events.js` and a port connection in `popup.js`.

I considered adding a port through the options page, but decided to drop it since it might have side effects we don't want.

**Comment by kalicki1** [comment]
Since it looks we are all set with this issue and everything seems to be working well in our tests, I will go ahead and close this up.
