### ISSUE TITLE
STOP spamming me with settings EVERY time the addon gets updated!!!

### ISSUE THREAD

**Issue by globus999** [privacy-tech-lab/gpc-optmeowt#206]
I have exactly ZERO interest for the addon to open a website page and spamming me with its settings every friggin time it gets updated. Either fix this or I'll remove the addon because it is clearly interfering with my privacy!!!!

**Comment by SebastianZimmeck** [comment]
Stay cool, @globus999, we got you, chief! :) Thanks so much for the PR @bdougherty! We will review it momentarily ...
