### ISSUE TITLE
Google Maps Loading Speed

### ISSUE THREAD

**Issue by juvtib** [privacy-tech-lab/gpc-optmeowt#207]
I noticed that if I have OptMeowt enabled, loading images in Google Maps is significantly slowed and my CPU spikes. For example, if I turn on satellite imagery and pan or zoom, those new tiles take longer to load with OptMeowt enabled in the extensions control panel. I'm guessing there are a million API calls for Maps and OptMeowt is jumping in front of every single one. I'm just wondering if there is some way to improve the subjective experience or balance the number of intercepted calls. For example, under a set of conditions, throttle the number of intercepted calls.

**Comment by SebastianZimmeck** [comment]
@juvtib, I just navigated to Google Maps, switched to the satellite view, and panned and zoomed for a few minutes. The CPU usage went up indeed, but I did not find much of a difference between OptMeowt enabled and OptMeowt disabled.

Are you using OptMeowt v2.0.0?

Which browser and browser version are you using?

**Comment by juvtib** [comment]
Let me try with the new release.

**Comment by juvtib** [comment]
Performance seems fine with the new version.
