### ISSUE TITLE
Test analysis mode

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/gpc-optmeowt#212]
Not sure yet where we'll collect this data, but there should be a representative sample of privacy flags collected.

My initial idea is just to install the extension on my regular web browser to collect enough real data via regular browsing.

(we can't do this until I finish the data logging system, privacy-tech-lab/optmeowt-browser-extension#155 )

**Comment by SebastianZimmeck** [comment]
This is taken care of in #219.
