### ISSUE TITLE
Update architecture readme

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#213]
We have a separate [architecture readme](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/main/README_ARCHITECTURE.md), which is intended to give a more detailed overview of our codebase. This document is currently out of date and needs to be updated. Once we have restructured our codebase to include the analysis mode, it is time to update this readme. In addition to @kalicki1 working on this, it is also worthwhile for @stanleymarkman and @OliverWang13  to chime in here so that everyone is familiar with the codebase.

**Comment by SebastianZimmeck** [comment]
It might be a good idea to use this document and update it concurrently with planning the addition of the analysis mode per issue #204.

**Comment by SebastianZimmeck** [comment]
Once the v3 issue is resolved, @kalicki1 will update the architecture readme.

**Comment by SebastianZimmeck** [comment]
Apart from the mv3 issues, if you could also close this out @kalicki1 (as part of your overall documentation that you mentioned in the call), that would be terrific. That way everyone is up to date on the current architecture.

**Comment by SebastianZimmeck** [comment]
@OliverWang13 is taking the lead on this preparing a draft architecture overview as our extension works under MV3. @sophieeng will also review, and @kalicki1 will confirm.

**Comment by OliverWang13** [comment]
I changed the simple layout to instead show what our MV3 file structure would appear as. Next I will work on changing the text body that describes what the files are doing.

**Comment by OliverWang13** [comment]
I added a low-level description of every file and I think this is mostly sorted. I will hold off on merging anything because files may change before the release and this will need to be updated.

**Comment by OliverWang13** [comment]
I have finished updating the readme and I will merge it, but I could leave this issue open in case there are changes before the next release.

**Comment by SebastianZimmeck** [comment]
Sounds good! We can add to this issue as necessary.

**Comment by OliverWang13** [comment]
@sophieeng and @Jocelyn0830 should both read over the current readme architecture in the main branch, and make sure everything looks correct and up-to-date. Afterwards, we can close this issue.

- [ ] @sophieeng has checked it over
- [ ] @Jocelyn0830 has checked it over

**Comment by sophieeng** [comment]
Both @Jocelyn0830 and I have read over this and it looks right. Closing issue.
