### ISSUE TITLE
Implement site analysis breakdown page and analysis popup and connect those to the backend

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#215]
Implementing the mock ups that were made in Issue #157. This issue is intended to be for the frontend shell, not passing information, storing the domain list, or searching for the US Privacy String.

**Comment by OliverWang13** [comment]
Below is the current design.
![Screen Shot 2021-08-20 at 12 50 34 PM](https://user-images.githubusercontent.com/82842273/130267331-acd883f8-966a-4560-88ce-2cffef08a2a5.png)
![Screen Shot 2021-08-20 at 12 50 44 PM](https://user-images.githubusercontent.com/82842273/130267337-92306724-38ae-40ec-8c3a-e5f962aff6f5.png)

For now, the compliance is decided with a coin flip and the dropdown menu reveals no information. I will look into our current system for storing and retrieving the domains to think about how it would be best implemented. Perhaps we could create an object with .prePrivacyString, .postPrivacyString, .dnsLink, and .signalSent that we can store. For now, I am just designing the page on our Domain List file, but the code can be taken and placed into an AnalysisBreakdown file or something similar. Some things that I implemented, while functional, are likely not optimal but work for the time being. There are also extraneous functions that I have yet to delete but I will clean up the code once soon.

**Comment by OliverWang13** [comment]
![Screen Shot 2021-08-21 at 7 24 19 PM](https://user-images.githubusercontent.com/82842273/130337210-c154439a-1655-413f-9453-ece681537bdd.png)
The icons can be changed to anything, I was just playing around with happy and sad looking cats. It should be easy to display DNS links and US Privacy Strings once it is decided how they will be stored and retrieved. Dark mode has "compliant" and "not compliant" looking the same, which might be better if we can choose 2 different colors so it looks different.

**Comment by SebastianZimmeck** [comment]
Nice! I would prefer simple checkmarks instead of the cats, though, for usability reasons. It was not immediately clear to me what the icons meant.

**Comment by OliverWang13** [comment]
![Screen Shot 2021-08-21 at 9 21 42 PM](https://user-images.githubusercontent.com/82842273/130338908-45bc6485-61d0-4e83-bb10-ff927433683b.png)

I agree that the checkmarks look a lot better than the cats.

**Comment by SebastianZimmeck** [comment]
Great! Let's discuss tomorrow the connection to the backend functionality, e.g., link identification (issue #194), US Privacy flag detection (issues #148, #158) and database (issue #201).

**Comment by OliverWang13** [comment]
An issue I am currently having is having the compliant/not compliant badges change colors when we switch to dark mode. Right now they turn to the same color. I have played around with our styles pages to create specific classes for the badges, but nothing successful yet.

**Comment by SebastianZimmeck** [comment]
#224 and #225 may play a bit into the UI design as well.

**Comment by OliverWang13** [comment]
![Screen Shot 2021-09-02 at 12 45 22 PM](https://user-images.githubusercontent.com/82842273/131884328-399865a3-1fc2-48cd-864e-976ade9d14db.png)
![Screen Shot 2021-09-02 at 12 45 58 PM](https://user-images.githubusercontent.com/82842273/131884336-f92a38b6-0a70-415f-8ac4-56deecd3abd5.png)

As of now, this is how the popup looks. I am currently unsure of the best way to put the Analysis Mode label on the top as shown in @kalicki1 's mockup.

**Comment by SebastianZimmeck** [comment]
> I am currently unsure of the best way to put the Analysis Mode label on the top as shown in @kalicki1 's mockup.

What exactly are you unsure about, @OliverWang13? Can you explain a bit more?

A few thoughts:
- Can you make the `Compliant`/`Not Compliant` labels smaller or do some other modification so that `CCPA Compliance Not Compliant` fits in one row?
- I feel the blue checkmarks should and the `Compliant` label should be green. I know you probably chose blue because of red/green blind people. But that is OK in this context as the label text and checkmark/vs cross makes it possible for colorblind users to distinguish.
- Change to "GPC Signal Sent" and "Analyzed Site List" to "All Analyzed Sites"

**Comment by OliverWang13** [comment]
![Screen Shot 2021-09-02 at 8 16 16 PM](https://user-images.githubusercontent.com/82842273/131931845-d8547fc5-a3d9-45ad-9c66-8bdf1fa578ec.png)

**Comment by SebastianZimmeck** [comment]
It's the right direction, but I feel the Analysis Mode button does not quite fit into the rest of the UI. Maybe, smaller, rounded corners, grey font, more along the lines of the Not Compliant label.

Also, we are in analysis mode and showing Analysis Mode. Does that make sense? Clicking on Analysis Mode actually leads to Protection Mode. Normally, I would think that the button showing something would lead to that. Here it is the opposite. It is probably still intuitively usable; when the user clicks on it they will see what's up. And it also would look weird if we are in analysis mode and have "Protection Mode" at the top (and vice versa).

**Comment by OliverWang13** [comment]
I think that I would prefer it showing the mode that it is currently in, and then you click on it to switch, but I am open to either. With the button being so large at the top it looks more like a label than a switch. I will change the button style.

**Comment by SebastianZimmeck** [comment]
Great! That all works for me.

**Comment by OliverWang13** [comment]
![Screen Shot 2021-09-02 at 9 12 17 PM](https://user-images.githubusercontent.com/82842273/131935621-bd8cd42f-c0c6-4957-9763-75764f766d2b.png)
Here it is in dark mode for a change.

**Comment by SebastianZimmeck** [comment]
@OliverWang13, if you are using any icon package, please add it to the end of the readme (generally with any libraries, packages, or other resources you are using; so we can easily find licensing information when we need it).

**Comment by OliverWang13** [comment]
I am not. Is there a chance that fairly generic symbols could be grounds for licensing issues even if they are not taken from a pack?

**Comment by SebastianZimmeck** [comment]
If you did not create it, then almost certainly someone else has a copyright for it. Ideally, use [Font Awesome icons](https://fontawesome.com/?utm_source=font_awesome_homepage&utm_medium=display&utm_campaign=fa5_released&utm_content=auto_modal) or any other package with MIT or similar license. It is also better to have some well-supported package as opposed to some possibly random icon.

**Comment by OliverWang13** [comment]
I did create them, so hopefully it is not an issue. If you would rather I use something else I can do that instead.

**Comment by SebastianZimmeck** [comment]
Then it is OK as is.

**Comment by SebastianZimmeck** [comment]
@stanleymarkman will provide an update here as discussed.

**Comment by OliverWang13** [comment]
The work done for this issue will be continued in #237, so I will close this issue.
