### ISSUE TITLE
Explore usage of Firefox incognito mode for analysis mode

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/gpc-optmeowt#218]
We discussed using Firefox's Incognito mode to create an isolated environment for analysis mode- free of cookies, GPC signals, and other clutter. Mozilla has an addon mode which allows extension developers to have their program run bifurcated- one instance in the regular browser, and an independent one in the incognito mode.

The new strategy in control.js makes this easier- we just need to 1. reconfigure extension to run independently in incognito and 2. detect incognito mode on extension load (in control.js, to enable modes.)

**Comment by SebastianZimmeck** [comment]
@stanleymarkman came across a Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1380812 and it may be that the mode we planned to use isn't actually supported at the moment.

**Comment by SebastianZimmeck** [comment]
@kalicki1 will look into this.

**Comment by kalicki1** [comment]
I have looked into using the `"incognito": "spanning"` and `"incognito": "split"` permissions for OptMeowt on both Firefox and Chrome. For some reason, Firefox rejects any attempt I make at opening a new incognito window via 

`browser.windows.create({ "url": null, "incognito": true }); `

with a lack of permission warning. Chrome runs this without issue and opens an incognito on install (this is how I am testing it at the moment).

@stanleymarkman, did you have this issue with both permsisions? I know that `split` is a known FF bug. Perhaps I missed something but I'm not sure what this could be, it looks like we may not be able to use incognito (either opening it or running an instance of OptMeowt in an incognito tab) if this does not work.

**Comment by SebastianZimmeck** [comment]
> Chrome runs this without issue and opens an incognito on install (this is how I am testing it at the moment).

Essentially, if we cannot get it to work in Firefox, we would need to think of something different than incognito mode.

**Comment by stanleymarkman** [comment]
@kalicki1 So far I've only been opening incognito tabs manually, but that is weird. Have you tried without the URL parameter?

**Comment by stanleymarkman** [comment]
It is also possible we need to add webNavigation to our permissions

**Comment by kalicki1** [comment]
@stanleymarkman, is there a FF equivalent of that ‘run in private window’? I wasn’t able to find one. 

Also, dropping the url parameter in my call doesn’t change the outcome. I still get a ‘Uncaught (in promise) Error: Extension does not have permission for incognito mode’ error. I do think we are also using the webNavigation permission.

**Comment by stanleymarkman** [comment]
@kalicki1 menu->addons+themes->extensions->click on OptMeowt and then 'allow run in private windows'. Kind of unintuitive, but they also seem to prompt users on install from webstore, which is nice.

**Comment by SebastianZimmeck** [comment]
We will address this later after we have finished the implementation of the analysis functionality. The simplest solutions is to tell the user that they should use a clean browser to work in analysis mode. That is not ideal, though. Better would be to use the existing browser in incognito mode.
