### ISSUE TITLE
Is it possible to implement the analysis mode for both Firefox and Chrome?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#221]
One question that occurred to me (and that may be already taken care of in #204; but just to make sure), how do we make it such that the analysis mode is available for Firefox only? 

As I see it, because we need to use APIs that are currently not available in Chrome, e.g., the [webRequest.filterResponseData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData) to decrypt HTTPS traffic that may contain the US Privacy String (correct me if I am wrong), the analysis mode will be only available in Firefox. Are we solving this distinction on the build level? In other words, the production build for Chrome will include just the protection mode and the production build for Firefox will include both the protection and analysis mode?

**Comment by SebastianZimmeck** [comment]
We are building specific versions for Firefox and Chrome. So, this would be resolved via the build process. We have not done this yet, though.

**Comment by SebastianZimmeck** [comment]
In the codebase, we can also have some if statements if necessary, e.g., that UI analysis elements are not displayed for Chrome.

**Comment by SebastianZimmeck** [comment]
Based on a point @notowen333 brought up in a different context, I am beginning to wonder whether we can also actually implement the analysis mode for Chrome as well. Essentially, the difference between Chrome and Firefox for our purposes is that Firefox is missing the [webRequest.filterResponseData()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData). But do we actually need that API to detect the US Privacy String cookie (and possibly the OptanonConsent cookie from OneTrust and similar cookies)? Cookies are a header that we should be able to see without the webRequest API, right? Not sure if we would need it for other implementations (issue #148). @stanleymarkman, could you look into that?

**Comment by SebastianZimmeck** [comment]
@kalicki1 will take the lead on this and @stanleymarkman will chime in as well.

**Comment by kalicki1** [comment]
At this point in time, I think it is easy to say that our `analysis` mode will only be able to run in Firefox. 

This issue will be relevant again when we get to issue #236, though only to make sure that when we implement a switch for `protection` to `analysis` and vice versa that it is not implemented for Chrome and only done for Firefox.
