### ISSUE TITLE
Connect various analysis mode components

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#230]
As we discussed today, we need to connect the various components to each other in the program flow (e.g., the Do Not Sell link analysis, current GPC status, sending GPC signal, ...). @kalicki1 will take the lead on this and @stanleymarkman and @OliverWang13 will chime in.

**Comment by kalicki1** [comment]
@OliverWang13, @stanleymarkman and I met today to discuss where we will be heading in the near future. Part of our discussion in how to connect all of our analysis components was to break down what type of data we will be saving and how to format it. A tentative outline for an analysis object structure is as follows: 

```
{
  "wired.com": {  // DOMAIN LEVEL
    0: {
      "FIRST": {  // All of the info here will be scraped if privacy flag found
        "COOKIES": {},
        "DO_NOT_SELL_LINK_EXISTS": false,
        "HEADERS": {},
        "URLS": {},
        "USPAPI": {},
        "USPAPI_LOCATOR": {}, // Not sure if we need this here
        "THIRD_PARTIES": {
          "https://eus.rubiconproject.com/usync.html?us_privacy=1---": {
            0: {
              "FIRST": {
                "COOKIES": {},
                "HEADERS": {},
                "URLS": {},
                "USPAPI": {},
                "USPAPI_LOCATOR": {}
              }, 
              "SECOND": { ... }
            }
          }
        }
      },
      "SECOND": { ... }
    }
  }
}
``` 

A more expansive version with some example data filled in would look like: 
```
{
  "wired.com": {  // DOMAIN LEVEL
    0: {
      "FIRST": {  // All of the info here will be scraped if privacy flag found
        "COOKIES": {
          "usprivacy": {
            domain: "www.wired.com",
            expirationDate: 1663019064,
            firstPartyDomain: "",
            hostOnly: true,
            httpOnly: false,
            name: "usprivacy",
            path: "/",
            sameSite: "lax",
            secure: false,
            session: false,
            storeId: "firefox-default",
            value: "1---"
          }
        },
        "DO_NOT_SELL_LINK_EXISTS": false,
        "HEADERS": {},
        "URLS": {},
        "USPAPI": {
          "uspString": {
            uspString: "1---",
            version: 1
          }
        },
        "USPAPI_LOCATOR": {}, // Not sure if we need this here
        "THIRD_PARTIES": {
          "https://eus.rubiconproject.com/usync.html?us_privacy=1---": {
            0: {
              "FIRST": {
                "COOKIES": {},
                "HEADERS": {},
                "URLS": {
                  "us_privacy": "1---"
                },
                "USPAPI": {},
                "USPAPI_LOCATOR": {}
              }, 
              "SECOND": { ... }
            }
          }
        }
      },
      "SECOND": { ... }
    },
    1: { ... }  // 2nd time visiting wired.com for an analysis cycle
  }
}
``` 

As a note, the "FIRST" and "SECOND" keywords refer to the order in which we pull the us privacy string and other privacy flags in relation to sending the GPC signal. I.e., "FIRST" is the data collected from the site without the GPC signal, and "SECOND" refers to the site data collected after the site is refreshed with the GPC signal.

**Comment by SebastianZimmeck** [comment]
That is a good starting point. A few comments:
- A lot of the data, e.g., `httpOnly`,`sameSite`, headers, ... we do not need. The data probably comes for free, and so we can collect it. But if there is implementation effort involved, I would suggest to only collect what we need.
- The "FIRST" and "SECOND" keywords, do not really describe what they refer to, right? Wouldn't "BEFORE_GPC" and "AFTER_GPC" or something like that be better?
- The object structure should also be extensible to accommodate other flags, e.g., OptanonConsent cookie (#225), Complianz CMP cookie ((#227), ...

**Comment by SebastianZimmeck** [comment]
Stanley is currently working on that.

**Comment by SebastianZimmeck** [comment]
Sub-issues of this issue are #225, #227, #228, and #229 ,and they will be addressed as part of this issue.

**Comment by kalicki1** [comment]
We are opening issue #233 in order to simplify our data so the frontend does not have to do any analysis of its own when rendering our results.

**Comment by SebastianZimmeck** [comment]
This issue is an architectural issue and dependent on resolving #225, #227, #228, and #229 first. Once they are essentially done, this issue will be connecting all the different functionalities from those.

#233 is not a dependency here but important in this context.

So, @kalicki1 will come back to this issue once the other ones are addressed.

**Comment by kalicki1** [comment]
Since this is essentially resolved sans handling signals from CMPs (the four issues mentioned above), I will go ahead and close this issue and leave those four particular issues open as their own stand-alone things.
