### ISSUE TITLE
Implement timestamps for each analysis step to be shown in console logs

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#235]
In order to make sure that the analysis has the order DNS link detected -> US Privacy String value detected -> GPC signal sent -> US Privacy String value change detected, we want to have timestamps for the console logs. So, the timestamps have to be created when the respective analysis steps are happening.

**Comment by kalicki1** [comment]
The last commit resolves this issue. As opposed to printing everything to the console, I have the timestamps automatically add to the `analysis_userend` object so it's possible to double check all the timings when we analyze our data.
