### ISSUE TITLE
Check performance of each `analysis` mode component

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#238]
I am going through each of the `analysis` mode features we have implemented and seeing how they perform on their own to try and weed out inefficiencies in the code. 

If any issues arise, I will write down some notes here and open new issues as appropriate. As a side note, it seems that resolving the previous performance issue when using `webRequest.filterResponseData()` already cut down most of the problems we have been seeing when using OptMeowt normally.

**Comment by SebastianZimmeck** [comment]
This issue is related to both performance in terms for accuracy as well as runtime performance.

**Comment by kalicki1** [comment]
I have been running a few tests and have some relatively positive news.

**Runtime performance**
To me it seems that we have solved our runtime performance issues. Nothing stood out to me as particularly inefficient or slow, and comparing the full analysis runtime to loading a page without OptMeowt seems to be pretty similar at this point (on my machine). The only note to make is my computer gets warm and kicks up the fans after around 15-20 sites while refreshing 3 times per site, but I suspect it's because we are making the extension read through every incoming piece of data. 

**Accuracy**
I ran two small tests on a subset of our validation set. 

First, I ran our first 8 domains numbered 3-11 in our spreadsheet and found no discrepancy between the values I got and what we had recorded. The only thing noteworthy is that if a site didn't have a DNS link and didn't have a us_privacy string, it always registered as having _not_ sent the GPC signal, which is not true. Since it was consistent all the way through, I don't think it would have affected the results in any way.

Second, I ran a test on a middle twenty domains I thought had a good variety to them, specifically those numbered 46-65. Of those, only one incorrectly registered to not have the DNS link, `Disqus.com`. Another, `espn.com` also registered that it was "missing" something incorrectly, but for some reason it is because the whole row in my spreadsheet is undefined (it will take some individual care to see why this is). The last weird case is `buzzfeed.com`'s us_privacy string, which saved as just null.

On the flip side of the coin, there were three new sites that now support the us_privacy string, `nbcnews.com`, `mashable.com`, and `latimes.com`. Even more astoundingly, the `latimes.com` actually flipped their us_privacy string after receiving the GPC signal. 

-- 

This is a fairly descriptive write up but might be useful to reference up until we run our official tests.

**Comment by kalicki1** [comment]
I have worked on a few changes as discussed in this issue and in #234 and reran a test on websites 25-55 on our validation set. Here are the outliers that didn't line up with what we had recorded.


## New Positives:
- `bloomberg.com` - now has a us_privacy string
- `theguardian.com` - now has a us_privacy string
- `mediafire.com` - now has a us_privacy string
- `businessinsider.com` - now has a us_privacy string (DNS link not found, but marked red on excel)
- `wired.com` - now has a us_privacy string, and a DNS link

## Missing us_privacy string:
- `espn.com` - **Missing us_privacy string.** This one is actually outside the set but next to abcnews.com, so maybe it was loaded as a part of that site? Makes sense because abcnews.go.com loads quite a few espn resources.
- `nypost.com` - Missing us_privacy string.

## Missing DNS links:
- `theguardian.com` - now has a us_privacy string, but missed a DNS link
- `mediafire.com` - now has a us_privacy string, but missed a DNS link (I checked the page myself; it looks like there isn't one there..)
- `disqus.com`
- `theatlantic.com` - We noted tag searching doesn't work (I had to scroll thru a semi-infinite scroll page to find it myself)

## Other cases:
- `huffPost.com` - has a USPAPI call, but returns null? I would count this as not having one, we marked it down that way and otherwise it lines up with our old data


## Summary

It seems the ones we need to worry about are:
- `nypost.com` 
- `disqus.com`
- `theguardian.com`

Putting aside issues related to infinite scroll pages (I believe `theatlantic` loads like this), the only real issue seemed to be `nypost.com`, for which I suspect I cut the analysis too short but I can't say for sure (it's easy to say a second pass would catch this, but do we want to do that extra work?).

`disqus.com` is also an outlier but it seems that its CDN `disquscdn.com` loaded its DNS link. I think we can catch cases like this by going through the data by hand, automating it may be hard since I don't want to mis-associate any 3rd party info with a 1st party.

That leaves `theguardian.com` as the only site I don't have an explanation for. To me it feels like it might be an infinite-scroll style issue, but I'll take this as the only missed value of the bunch (plus maybe `nypost`) for a ~28/30?

**Comment by SebastianZimmeck** [comment]
Thanks, @kalicki1! That is great! Let's discuss later ...
