### ISSUE TITLE
Safari version

### ISSUE THREAD

**Issue by andrewcrook** [privacy-tech-lab/gpc-optmeowt#241]

**Comment by kalicki1** [comment]
Thanks for opening this up @andrewcrook, we've been floating this idea for a while! Glad to see we aren't the only ones hoping for a Safari extension.

We'll start to look into making this happen. Keep your eyes out for updates on this issue and hopefully the next full release will include Safari support 🚀

**Comment by SebastianZimmeck** [comment]
Closing as we do not have the bandwidth at the moment.
