### ISSUE TITLE
Fix overflowing URL in popup in analysis mode

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#243]
In the analysis mode popup long URLs are not showing completely. Not sure how to solve this. Make it smaller? Just show the second level domain? Make it scrollable? Start at the beginning and just show as much as possible so that it at least does not show just the middle as it currently is. 

Also, if this is a problem in protection mode as well, we should fix it there too.

**Comment by kalicki1** [comment]
I was messing around with some simple solutions to this problem and came up with three different options to solve this, each with their own quirks. Here they are:

### 1. With default UIKit text break (apparently at hyphens)
<div>
<img src="https://user-images.githubusercontent.com/60238705/143952851-2b54ba1a-12e6-4607-8195-872d4f98d5b6.png" width="200">
<img src="https://user-images.githubusercontent.com/60238705/143952850-95bc1fbd-6dab-48a7-a3e9-e0e2245dffe4.png" width="200">
<img src="https://user-images.githubusercontent.com/60238705/143952847-5be260c5-d64d-4bb7-bcc8-b904213606e4.png" width="200">
</div>

### 2. With standard UIKit truncation (w/ `display: inline-block;`)
<div>
<img src="https://user-images.githubusercontent.com/60238705/143953933-883c769c-99de-4b87-a616-4de6fbc309a6.png" width="200">
<img src="https://user-images.githubusercontent.com/60238705/143953928-004e0722-0e46-45cf-bc3a-00c3e240e49f.png" width="200">
<img src="https://user-images.githubusercontent.com/60238705/143953931-2c77b4c1-f656-4a78-a62e-7fd333c67f18.png" width="200">
</div>

### 3. With an arbitrary overflow wrap (w/ `display: inline-block;`)
<div>
<img src="https://user-images.githubusercontent.com/60238705/143953775-1e2d8fbd-7b87-405c-88c3-629bc94d4873.png" width="200">
<img src="https://user-images.githubusercontent.com/60238705/143953776-8d27d823-82f5-4aa8-8415-c5abc4529c7d.png" width="200">
<img src="https://user-images.githubusercontent.com/60238705/143953777-35d4332c-24c3-40b1-804a-bd821ae09999.png" width="200">
</div>

<br>

Let me know if anyone has any preferences for how this should look, I'll push the corresponding changes then. Personally, I think options 1 or 2 could work. In particular for 1, I don't think there are many long domain names that would cause such a visual artifact as the last example I provided (that one is the only one I could find that overflowed in that way).

**Comment by SebastianZimmeck** [comment]
Great, @kalicki1! 

> Personally, I think options 1 or 2 could work (leaning towards 2).

Sounds good to me!

**Comment by OliverWang13** [comment]
I agree either 1 or 2 could work, do what you think is best @kalicki1.

**Comment by kalicki1** [comment]
I decided on keeping the changes from my 2nd option and pushed the changes. I'll go ahead and close this issue out since we're all set with it.
