### ISSUE TITLE
Omit compliance result in popup and settings page

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#244]
Currently, in analysis mode there is an overall result whether a site is compliant or not. For the time being, we can just omit the compliance result in the popup and in the settings page. There are two issues:

1. The result is shown before the analysis even runs
2. We need to figure out for every combination of Do Not Sell link detected, US Privacy String detected, etc. whether that is a compliant, non-compliant, or other (say, not applicable) combination. 

Fixing these things may take some time. So, for the time being, we can just remove the UI elements. Once done, we can leave this issue open, and do a bigger fix later on when we have more time.

**Comment by kalicki1** [comment]
I removed the compliance result element from both the popup and the settings page in my last commit. Since we are all set here, I'll go ahead and close this issue out.
