### ISSUE TITLE
Implement showing the detected US Privacy String in the UI

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#246]
There are situations in analysis mode where it is informative to show the actual US Privacy String (before and after sending the GPC signal) in the UI.

Most notably, if a user is not located in California, the String may be `1___` because the website only applies the CCPA to users from California. That is perfectly fine, but we are showing an X in the UI. In this case it may be helpful to see the actual String as that case is not a case of non-compliance but rather only a case of not applying the CCPA, which would become more clear seeing the String.

We would show the String in both the popup as well as in the settings page.

@kalicki1 mentioned that it is likely easy to do. However, if it takes a longer time or is complicated, I am also fine dropping such feature. We will address the case described by adding some language to the analysis settings page UI in any case.

**Comment by SebastianZimmeck** [comment]
@kalicki1 is taking the lead on this, and @OliverWang13 may assist on the UI end.

**Comment by kalicki1** [comment]
I have gone ahead and implemented this based on what I thought would be useful for our own analysis purposes. Some visual changes and text-rendering decisions might be changed in the future as we prepare for a release. 

Here are some screenshots of how everything looks at the moment: 

<div>
<img width="250" alt="Screen Shot 2021-12-07 at 1 47 11 PM" src="https://user-images.githubusercontent.com/60238705/145090347-b0fcf751-1302-4a81-b373-c3cc0b552ed5.png">
<img width="250" alt="Screen Shot 2021-12-07 at 1 48 54 PM" src="https://user-images.githubusercontent.com/60238705/145090252-ff0cee7f-2e75-49f2-bb31-806b170a9a95.png">
</div>

<div>
<img width="250" alt="Screen Shot 2021-12-07 at 1 46 04 PM" src="https://user-images.githubusercontent.com/60238705/145089777-21087e89-9e6a-4e0b-9a95-4a8eb3d07539.png">
<img width="250" alt="Screen Shot 2021-12-07 at 1 46 23 PM" src="https://user-images.githubusercontent.com/60238705/145089786-b3182386-4b00-4a4f-8990-70ae8b347216.png">
</div>

<img width="500" alt="Screen Shot 2021-12-07 at 1 57 38 PM" src="https://user-images.githubusercontent.com/60238705/145089804-d604577f-5295-448a-81c4-af18defc9e2b.png">

Let me know if anyone has any thoughts or suggestions on improvements.

**Comment by SebastianZimmeck** [comment]
Great, @kalicki1!

**Comment by kalicki1** [comment]
Since we're all set with this issue I will go ahead and close it out.
