### ISSUE TITLE
Added keyboard shortcuts and icon color change to `Analysis Mode`

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#247]
Recently I pushed a commit that I discussed with @OliverWang13 which might make running our `Analysis Mode` tests easier to do. I added keyboard bindings for starting and halting the analysis tests while in `Analysis Mode` only. Here they are:

- `Alt+Shift+A`—runs `a`nalysis (eq. to clicking `Run Analysis` in popup)
- `Alt+Shift+S`—`s`tops analysis (eq. to clicking `Stop Analysis` in popup)

I also added a yellow OptMeowt icon which turns on when we are currently "running analysis." It shuts off (turns blue) when we press "stop analysis" in order to visually signify that we are ready to navigate away from the current site. This will help ensure we don't mis-assign our data to the wrong domain since we have decided to make this process manual. (Reminder: users **must** "stop analysis" prior to changing sites)

At the moment there is nothing to do here. I just wanted to open an issue to make everyone aware that this functionality is here. If no one has any suggestions on changing anything (i.e., the actual key bindings), we can go ahead and close this.

**Comment by SebastianZimmeck** [comment]
Great! Thank you, @kalicki1! Could you add the keyboard bindings to the readme (maybe, in the developer section)?

**Comment by kalicki1** [comment]
Thanks for the suggestion @SebastianZimmeck, I added a small "Keyboard Shortcuts" section under "Developer Guide."

**Comment by SebastianZimmeck** [comment]
Nice!
