### ISSUE TITLE
Release for Microsoft Edge Add-ons

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#251]
Let's look into the process for releasing OptMeowt on the Edge Add-ons store. Hopefully, it should only take minor changes to the Chrome version as Edge is now based on Chromium 🚀

**Comment by kalicki1** [comment]
A point @SebastianZimmeck brought up today is we should check whether or not Microsoft still allows Manifest V2 extensions on their store at this point in time. @SebastianZimmeck also mentioned we should wait until he can make a privacy-tech-lab account for the Edge Add-ons Store. 

@OliverWang13 will take charge on this issue once this is all set and we know if they accept V2 extensions.

**Comment by OliverWang13** [comment]
To publish we need to create a developer account here: https://partner.microsoft.com/dashboard/microsoftedge/public/login?ref=dd

Steps can be found on this page under "Submit your extension to the Microsoft Edge Add-ons Website":
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

Another very useful document here on how to port a chrome extension to Microsoft edge:
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

I took a look at the supported API list and we should have no problem there. They suggest sideloading the extension on Microsoft after making a few tweaks to make sure that it works. I can download edge and test it out if that would be useful.

**Comment by SebastianZimmeck** [comment]
As we just discussed, I am going to open a Microsoft Edge account, @OliverWang13 and @kalicki1 will provide the release code, and I will put it in.

**Comment by SebastianZimmeck** [comment]
OK, I have created an account. So, whenever you are ready, @OliverWang13 or @kalicki1, feel free to create a release with zip source files. If Microsoft does not require Manifest v3, we can do it even before the switch. Then update once we moved to v3.

**Comment by kalicki1** [comment]
I'm double checking the requirements that @OliverWang13 outlined above, and it doesn't seem like we need to change much, if at all. 

The only thing I'm unsure about is whether we need to modify/add `description` or `short_description` keys to our manifest file or if we can upload OptMeowt's metadata after uploading to the Edge store. @SebastianZimmeck, I'm not sure if you can see this in the developer portal. Further, the "porting to Edge" link specified an `update_url` manifest key and how to add it, though it seems to me that this url will be generated after we upload so I'm not sure if we need it for approval. 

If we don't need any of these changes, @SebastianZimmeck I believe we can just try to reuse our old v2.0.1 release zips from a few months ago as-is. Let me know if the store asks for them to be repackaged in a different way.

**Comment by SebastianZimmeck** [comment]
Thanks, @kalicki1. I tried but received the following error:

> The following checks failed:
> Package acceptance validation error: The ZIP file doesn't contain the manifest.json file. 

It seems the Edge store is simply looking for a file named "manifest.json," which we do not have. Not sure if we can simply duplicate that. But that may cause us some additional work (or may cause confusion).

**Comment by SebastianZimmeck** [comment]
Closing as we do not have the bandwidth at the moment.
