### ISSUE TITLE
Can we display an update notification to existing users to advertise our usability study?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#258]
As we want to explore whether our UI is usable we need to recruit users for our usability study. These could be either new users or existing users (which would be a bit more nifty). As far as I know, upon updating a Chrome extension on the Chrome Web Store, the update is pushed to all users.

1. Is that true?
2. Is that also true for Firefox?
3. If 1 and/or 2 is true, what notification functionality can we use to display a notification to users with a link to our site for signing up for our study?

@sophieeng will take the lead here, and @kalicki1 and @OliverWang13 will assist. We can discuss more when we meet later this week.

**Comment by SebastianZimmeck** [comment]
More important than the actual notification technology used here (some built-in API, library, ...) is that it works ideally for both Chrome and Firefox. It can even as simple as temporarily changing the pop up html, e.g., a the top presenting a header with a link to the sign up page for our study.

**Comment by SebastianZimmeck** [comment]
As discussed today, @sophieeng will look into whether it is possible to use the settings page as it seems to be the default behavior that when an extension is updated, the settings page is opened. We could then just have a "Breaking News" banner written in html at the top of our settings page announcing our study with a link to the sign-up page for participants. Alternatively/additionally, we may just sign up new users, in which case we will not need any modification to the codebase.

**Comment by SebastianZimmeck** [comment]
@sophieeng will look into how to test the notification functionality, which is a bit tricky because we may actually need to update our extension on the Chrome Web Store to check whether it works. We do not want to confuse or annoy our users, though, by showing them the settings when this is actually just a test.

One option may be to have a separate extension on the Chrome Web Store to just test this. Though, this may be overkill.

Or maybe, we can do some if statement to display the settings screen only to Vivaldi users or something like that. So, that this test just shows up for a very small number of users. Or code some other kind of condition.

**Comment by SebastianZimmeck** [comment]
@sophieeng made good progress on this issue. We decided today that @sophieeng will finalize her implementation and test it locally. Then, we can decide at a later point whether we want to continue this path, which would be the case if we want to sign up existing users. If we decide so, we would need to test the functionality via deployment as a (different) dummy app on the Chrome Web Store. Either way, as we agree today, we are going to sign up new users via Prolific, for which we would not need the new notification functionality (but even in that case it is an opportunity for @sophieeng to work with and get to know the codebase).

**Comment by SebastianZimmeck** [comment]
We decided to no longer have the notifications. So, @sophieeng will push to the issue-258 branch what she currently has and then close this issue.

**Comment by sophieeng** [comment]
I have pushed my changes ([648d048](https://github.com/privacy-tech-lab/gpc-optmeowt/commit/648d048f29838872b6dc03d5e3278ba69ad372bc)). This code will pop up a survey module on every update, but not on install. This was only tested locally using the "Update" button in the Chrome extensions page.
