### ISSUE TITLE
Do we need to make code changes due to Firefoxs' changed install process?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#264]
I received the following from Mozilla. It does not look like we need to make changes as we are not distributing from a first party site. However, can you scope this out, @sophieeng? @kalicki1 and @OliverWang13 can assist.

> Starting with Firefox 100, Firefox will be requiring user activation to start an add-on install.  If you are distributing your add-on from a third party site, you may need to change your install flows.  If this applies to your add-on(s), we recommend that you test your install flow using Firefox 100.  Firefox 100 Beta can be downloaded from  [mozilla.org](https://links.email.mozilla.org/els/v2/LaKZCw9VYhK/M3dMRU9BeXpzQmZYM1pCWm1SNEhseGJzRVRjUVFpL1NudG5YZHl1bTNHc2srZzBjVlBaQndCZFFsQjd6eWxJNXdTMnFIOHNyRHVGWlAvZ01vM21NeEE9PQS2/).
> 
> If changes are needed, you will need to use one of the following approaches on your website:
> 
> Link directly to the add-on XPI using a standard Web link
> From a user initiated event handler (such as a click handler) using window.location to point directly to the add-on XPI
> 
> Additionally, InstallTrigger.install will be removed as of Firefox 102.  This API was never officially supported in Firefox, and remaining users will need migrate to one of the above approaches.  In Firefox 100 and 101 this API will still be available, but will require user activation as described above.  We will also include deprecation warnings in the Web Console.

**Comment by sophieeng** [comment]
No, we do not need to make any code changes. For the Firefox browser, OptMeowt is only distributed through Firefox Browser Add-ons (AMO). AMO is Mozilla's official Firefox add-ons distribution platform. We don't offer any self-distribution options, therefore not distributing through a third party. We also do not use InstallTrigger.install.

**Comment by SebastianZimmeck** [comment]
Excellent! Thank you, @sophieeng!
