### ISSUE TITLE
Connect 3rd party toggles in popup to their respective domains

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#266]
> the only outstanding issue on this is that the 3rd-party toggles generated in the popup connect to the 1st party domain for some reason. This can be sorted out at another time or when testing the whole extension.

OK, feel free to open an issue or keep track of it in another way.

_Originally posted by @SebastianZimmeck in https://github.com/privacy-tech-lab/gpc-optmeowt/issues/175#issuecomment-1094087622_

**Comment by kalicki1** [comment]
My last commit resolved this issue. I will go ahead and close this out as the changes are on branch issue-175 (tagging #175).
