### ISSUE TITLE
Make tour optional

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#267]
As discussed today, showing the tour upon install should be optional. Instead of displaying it to all users, we will show it only to users who are interested. More specifically, @sophieeng will implement a button, icon, or even just a link "Take Tour" on the popup and wire it to the tour. All logic exclusively related to the current mandatory showing will be removed (per #265).

**Comment by OliverWang13** [comment]
I did some work on this issue and pushed them to issue-267. I made it so the tutorial no longer pops up automatically when you visit the options page for the first time. I also added a button to the popup that links to the options tutorial. (The question mark button links to the page shown in the second picture).
![Screen Shot 2022-05-27 at 10 40 38 AM](https://user-images.githubusercontent.com/82842273/170722143-c78d71d6-d2ac-4940-8603-1992e475d4a5.png)
![Screen Shot 2022-05-27 at 10 40 58 AM](https://user-images.githubusercontent.com/82842273/170722157-524faa29-0167-49f1-943c-755e95744896.png)
.

**Comment by SebastianZimmeck** [comment]
Nice! The question mark is a nice touch.

> I made it so the tutorial no longer pops up automatically when you visit the options page for the first time.

Is the tutorial popping up automatically automatically anywhere else? Let's disable the automation anywhere. Especially, the last time @sophieeng mentioned that there are two tours/tutorials; one upon install and one upon accessing the settings page. Neither should come up automatically.

**Comment by OliverWang13** [comment]
I now disabled both of the tours automatically popping up.

**Comment by SebastianZimmeck** [comment]
Excellent!

Feel free to open a PR.
