### ISSUE TITLE
Omit settings page on install

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#268]
Is there a way that we can omit showing the settings page upon install? If so, it may be a good idea to do it. There is probably not that much use anyways for showing that page as most users are probably not interested in changing the settings at that point.

Is the current default upon install "send GPC signal to all pages"? If not, let's change it to that (assuming that we are no longer showing the settings page upon install).

**Comment by OliverWang13** [comment]
It is definitely possible to omit the settings page. However, would we like to also get rid of the tutorial? (Issue #267) If so, it would be easier to omit the settings page after this change has been made. I will tag and assign @sophieeng as this might be a good issue for us to discuss.

**Comment by SebastianZimmeck** [comment]
Yes, getting rid of both is the preferable solution in my mind.

**Comment by SebastianZimmeck** [comment]
Correct!

**Comment by SebastianZimmeck** [comment]
> so this means no button that will pop up the tutorial, correct

I mean, just to clarify, there should be some UI element in the popup (button, link, ...) to bring up the tutorial and the settings. Just, the tutorial and settings should not pop up automatically upon install (or any other action except the user clicking the button, link, ...).

**Comment by sophieeng** [comment]
I have removed the code that opened the Options page on install. It will not pop up anymore on its own.

@SebastianZimmeck mentions setting the default to "send GPC to all pages" in this issue. If that is still for this issue I can try to take care of it.

**Comment by SebastianZimmeck** [comment]
> @SebastianZimmeck mentions setting the default to "send GPC to all pages" in this issue

Yes, that would be great, @sophieeng!

**Comment by sophieeng** [comment]
GPC already does automatically send to all web pages, as confirmed by @OliverWang13.

**Comment by SebastianZimmeck** [comment]
Great! Then, nothing to do in that regard.

**Comment by sophieeng** [comment]
Both instances of code causing the Options page to appear on install were removed and merged to main. I am closing the issue.
