### ISSUE TITLE
Fix enable-disable button functionality

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#277]
When testing a few things I found that the enable-disable button can disable the extension, but then locks the popup so you can not enable the extension again. When the "pause" button is clicked in the first image, the page switches to the second image where nothing can be interacted with.
![Screen Shot 2022-05-27 at 10 52 33 AM](https://user-images.githubusercontent.com/82842273/170731807-46407839-75c2-48eb-ac77-7d619d06c6a8.png)
![Screen Shot 2022-05-27 at 10 52 39 AM](https://user-images.githubusercontent.com/82842273/170731818-cc6ec5c8-eec7-4d59-b187-38bb0d28593f.png)

**Comment by OliverWang13** [comment]
From what I can tell, I think I have found 2 issues that we are facing. The first is that the message that says "Extension Disabled" ends up covering the enable-disable button so we can not press it. The second is that the listener only evaluates `isEnabled` when the popup dom content is loaded, so you can not enable and disable without closing the popup first.

**Comment by SebastianZimmeck** [comment]
Good find, @OliverWang13!

**Comment by OliverWang13** [comment]
This has been figured out, so the issue will be closed.
