### ISSUE TITLE
Include study install confirmation code in settings

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#282]
For our usability study, let's include a confirmation code on the settings page that study participants give to us ensure that they have installed OptMeowt. We can discuss on Monday.

**Comment by sophieeng** [comment]
Code for just the text of the code. There's a small issue where users cannot highlight text on the Settings Page which means they won't be able to copy/paste. I will look into solving that or creating a button that will automatically copy the code when clicked.

**Comment by sophieeng** [comment]
When the 'Copy Code" button is clicked it will copy the confirmation code onto the user's clipboard.

Code has been merged and I am closing the issue.
