### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#283]
While redoing the readme architecture, I found some files we may no longer be using, so I will go through them to identify them and delete them if they are safe to delete. This issue can probably be done quickly and might be best tackled after the release is ready to avoid deleting files that others are working on.

I also think that we have some lines of code that don't do anything as of MV3 and this could be a good time to go through and clean that up. Possibly, we could go through commented code and take out anything that does not seem necessary to include.

**Comment by SebastianZimmeck** [comment]
Yes! Excellent idea, let's do that.

**Comment by OliverWang13** [comment]
This issue would be best dealt with after closing out #273 to make sure nothing is deleted that is useful.

**Comment by SebastianZimmeck** [comment]
Here are two source files --- [analysis-view.html](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/9f9e47b8efdae9a04785e06a0c18550641ad2701/src/options/views/analysis-view/analysis-view.html) and [analysis-view.js](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/be211693f7653638c31c6691cd3ab44d9a2b0ab3/src/options/views/analysis-view/analysis-view.js) ---that have outdated developer information. @Jocelyn0830, let's remove the lines, 

"Copyright (c) 2021 Kuba Alicki, Stanley Markman, Oliver Wang, Sebastian Zimmeck" 

make it like in the other source files. We always keep the up-to-date list of contributors in the readme.

**Comment by Jocelyn0830** [comment]
Code refactoring finished
