### ISSUE TITLE
Restructure code for Firefox MV2 and Chrome MV3

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#288]
Opening this issue to keep track of what needs to be done to restructure our MV3 code to MV2.

**Comment by OliverWang13** [comment]
- [ ] Change manifest version
- [ ] return service worker text to script in manifest (if service workers are not supported in MV2)
- [ ] collapse host permissions and permissions into permissions
- [ ] collapse content security policy
- [ ] return action API to browser_action
- [ ] collapse web-accessible resources
- [ ] change scripting.executeScript to tabs.executeScript (if not working with MV2)
- [ ] Return service worker to background page (if service workers not supported in MV2)
- [ ] Declarative net request to web request (if DNR is not supported in MV2)
- [ ] Search for more errors

**Comment by OliverWang13** [comment]
> You meant the other way around, right?

No, this is for adapting our Optmeowt MV3 version to work with firefox, so the code bases are not too different and can all be found on one Github release

**Comment by SebastianZimmeck** [comment]
OK, so technically this would be still MV3 as I understand it (just "Firefox MV3"). Firefox [talks about](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/) "Why are we adopting MV3?" etc. So, Firefox will adopt MV3, just will include some MV2 APIs that Chrome does not under their MV3. (Clarifying my understanding here)

**Comment by OliverWang13** [comment]
To my understanding, Firefox does not support MV3 yet so we would have to return to MV2, but try to keep similar file structure that we are using for MV3.

**Comment by OliverWang13** [comment]
This issue seems to mostly be working with a few small issues.

- [ ] darkmode looks a little weird (might be a problem in main too)
- [ ] Headers sometimes send when they aren't supposed to

But from what I can tell that is it. I have looked into the header issue for a while and it might benefit from another set of eyes (@kalicki1).

**Comment by SebastianZimmeck** [comment]
> Headers sometimes send when they aren't supposed to

That seems important to fix.

**Comment by OliverWang13** [comment]
Yes, definitely.

**Comment by OliverWang13** [comment]
Actually, the visual bug is not very important and this branch can probably be merged, so I will open a pull request.

**Comment by OliverWang13** [comment]
I merged this and I think this issue can be closed.
