### ISSUE TITLE
Identify MV3 errors post-merge

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#289]
I am opening this issue as a place for us to report bugs we find after the big MV3 merge, and then we can open new issues to tackle big bugs or can do quick fixes for smaller bugs. Bugs should be reported in a checklist and then checked off when dealt with.

**Comment by OliverWang13** [comment]
First two things I noticed: 

- [ ] The popup tutorial button does not work consistently
- [ ] The enable/disable popup functionality has stopped working as well

**Comment by OliverWang13** [comment]
Note about the popup tutorial button, in the issue-288 branch it seems to work fine on Firefox, it likely is messed up due to how Mv3 handles listeners? The main issue is when you are on the settings page and hit the tutorial button it does not pop up, but it does change `TUTORIAL_SHOWN` to false so the next time you navigate to the page the tutorial is shown

**Comment by SebastianZimmeck** [comment]
The icon does not change at all; not on sites with .well/known but it also does not have the brief green glow around the edges when sending a GPC signal.

**Comment by OliverWang13** [comment]
I am finding that the "domains receiving signals" does not seem to be working for me, and I will create a new working list of the bugs that we know of.

**Comment by OliverWang13** [comment]
- [ ] tutorial button not working
- [ ] popup symbol not changing
- [ ] domains receiving signals not working

**Comment by OliverWang13** [comment]
I fixed two of the issues, the only outstanding one I know of is 

- [ ] popup symbol not changing

**Comment by OliverWang13** [comment]
From what I can tell, analysis mode on firefox seems like it may have stopped functioning? In theory it shouldn't have any issues because I don't think Kuba messed with that code, but I will look into it further.

**Comment by OliverWang13** [comment]
I will be creating a checklist of OptMeowt features that we want to make sure are working.

**Comment by OliverWang13** [comment]
Useful snippets: 
`__uspapi('getUSPData', 1, (data) => { console.log("USP Data: ", data); });`
`navigator.globalPrivacyControl`

**Comment by OliverWang13** [comment]
FOR @OliverWang13  CHECKLIST

Chrome:

From settings page:
 

- [ ] Domain List button works

- [ ] Domain list build properly (no visual issues, visit a new site and see if it pops up next time you visit domainlist)
- [ ] Domains can be toggled on/off
- [ ] About button works
- [ ] Enable setting works (reflected in popup, visit site and see if headers and dom are sent)
- [ ] Domain list setting works (turning a site off from domain list stops the signals - turn a site off and check)
- [ ] Disable settings works (reflected in popup, visit site and see if the signal is sent)
- [ ] For the different settings, choose a setting then navigate off of the page and reopen it, has the setting stayed the same?
- [ ] Export domain list works
- [ ] Import domain list works


From popup:

- [ ] Disable, enable button works visually
- [ ] Disable, enable button effectively sends or doesn't send signals
- [ ] More button brings you back to settings page
- [ ] Help button opens tutorial
- [ ] Help button while options page is open opens tutorial
- [ ] Toggle send signal on and off, check if it is reflected on the site when you reload it
- [ ] Toggle send signal on and off, check if it is reflected in the domainlist
- [ ] Visit big site and check for 3rd party domains
- [ ] Test toggling on and off these 3rd party domains, check domainlist
- [ ] Check site that has the well-known property (https://global-privacy-control.glitch.me/, for example), make sure the well-known tab works
- [ ] Domain list popup button works
- [ ] Toggle darkmode, make sure it is consistent on the settings page

Firefox:

From settings page:
- [ ] Domain List button works
- [ ] Domain list build properly (no visual issues, visit a new site and see if it pops up next time you visit domainlist)
- [ ] Domains can be toggled on/off
- [ ] About button works
- [ ] Enable setting works (reflected in popup, visit site and see if headers and dom are sent)
- [ ] Domain list setting works (turning a site off from domain list stops the signals - turn a site off and check)
- [ ] Disable settings works (reflected in popup, visit site and see if the signal is sent)
- [ ] For the different settings, choose a setting then navigate off of the page and reopen it, has the setting stayed the same?
- [ ] Export domain list works
- [ ] Import domain list works

From popup:
- [ ] Disable, enable button works visually
- [ ] Disable, enable button effectively sends or doesn't send signals
- [ ] More button brings you back to settings page
- [ ] Help button opens tutorial
- [ ] Help button while options page is open opens tutorial
- [ ] Toggle send signal on and off, check if it is reflected on the site when you reload it
- [ ] Toggle send signal on and off, check if it is reflected in the domainlist
- [ ] Visit test server site and check for 3rd party domains
- [ ] Test toggling on and off these 3rd party domains, check domainlist
- [ ] Check site that has the well-known property (https://global-privacy-control.glitch.me/, for example), make sure the well-known tab works
- [ ] Domain list popup button works
- [ ] Toggle darkmode, make sure it is consistent on the settings page

Analysis:
- [ ] Change to analysis mode, clear cookies
- [ ] Navigate to site (preferably one that respects GPC and we already know the ground truth for, like nba.com)
- [ ] Run analysis based on methodology outlined in our data spreadsheet
- [ ] Compare the two, they should be the same

**Comment by OliverWang13** [comment]
FOR @Jocelyn0830  CHECKLIST

Chrome:

From settings page:
 

- [ ] Domain List button works

- [ ] Domain list build properly (no visual issues, visit a new site and see if it pops up next time you visit domainlist)
- [ ] Domains can be toggled on/off
- [ ] About button works
- [ ] Enable setting works (reflected in popup, visit site and see if headers and dom are sent)
- [ ] Domain list setting works (turning a site off from domain list stops the signals - turn a site off and check)
- [ ] Disable settings works (reflected in popup, visit site and see if the signal is sent)
- [ ] For the different settings, choose a setting then navigate off of the page and reopen it, has the setting stayed the same?
- [ ] Export domain list works
- [ ] Import domain list works


From popup:

- [ ] Disable, enable button works visually
- [ ] Disable, enable button effectively sends or doesn't send signals
- [ ] More button brings you back to settings page
- [ ] Help button opens tutorial
- [ ] Help button while options page is open opens tutorial
- [ ] Toggle send signal on and off, check if it is reflected on the site when you reload it
- [ ] Toggle send signal on and off, check if it is reflected in the domainlist
- [ ] Visit big site and check for 3rd party domains
- [ ] Test toggling on and off these 3rd party domains, check domainlist
- [ ] Check site that has the well-known property (https://global-privacy-control.glitch.me/, for example), make sure the well-known tab works
- [ ] Domain list popup button works
- [ ] Toggle darkmode, make sure it is consistent on the settings page

Firefox:

From settings page:
- [ ] Domain List button works
- [ ] Domain list build properly (no visual issues, visit a new site and see if it pops up next time you visit domainlist)
- [ ] Domains can be toggled on/off
- [ ] About button works
- [ ] Enable setting works (reflected in popup, visit site and see if headers and dom are sent)
- [ ] Domain list setting works (turning a site off from domain list stops the signals - turn a site off and check)
- [ ] Disable settings works (reflected in popup, visit site and see if the signal is sent)
- [ ] For the different settings, choose a setting then navigate off of the page and reopen it, has the setting stayed the same?
- [ ] Export domain list works
- [ ] Import domain list works

From popup:
- [ ] Disable, enable button works visually
- [ ] Disable, enable button effectively sends or doesn't send signals
- [ ] More button brings you back to settings page
- [ ] Help button opens tutorial
- [ ] Help button while options page is open opens tutorial
- [ ] Toggle send signal on and off, check if it is reflected on the site when you reload it
- [ ] Toggle send signal on and off, check if it is reflected in the domainlist
- [ ] Visit test server site and check for 3rd party domains
- [ ] Test toggling on and off these 3rd party domains, check domainlist
- [ ] Check site that has the well-known property (https://global-privacy-control.glitch.me/, for example), make sure the well-known tab works
- [ ] Domain list popup button works
- [ ] Toggle darkmode, make sure it is consistent on the settings page

Analysis:
- [ ] Change to analysis mode, clear cookies
- [ ] Navigate to site (preferably one that respects GPC and we already know the ground truth for, like nba.com)
- [ ] Run analysis based on methodology outlined in our data spreadsheet
- [ ] Compare the two, they should be the same

**Comment by OliverWang13** [comment]
This should be resolved, so I will close it
