### ISSUE TITLE
Remove search functionality

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#290]
I just tried using the domain search functionality, and it was a bit too much for the extension. I have 7,000+ domains and so it became unresponsive. When I re-started the browser it worked again. My suggestion would be to remove the search functionality. Since the sorting is alphabetic, it is also possible to find domains that way. This can wait until all mv3 issues are resolved.

Maybe, test on your end what your experience is.

@OliverWang13, can you take the lead here and @kalicki1 can assist?

<img width="1013" alt="Screen Shot 2022-06-15 at 7 12 51 PM" src="https://user-images.githubusercontent.com/11034003/173957820-9ccd791a-a5c8-4690-a582-f1da34306458.png">

**Comment by SebastianZimmeck** [comment]
@sophieeng brought up the idea to have a small list to search, maybe, reset it every day. However, we discussed that this may be too complex for a fairly marginal gain of functionality. So, just completely removing it seems the way to go.

**Comment by sophieeng** [comment]
The Domain List search bar has been removed.

The Instagram.com website that showed up when the Domain List with loading has been replaced with Loading...

The code has been merged and I'm closing the issue.
