### ISSUE TITLE
Re-add File-saver?

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#298]
I remember that we removed file-saver from our npm a while ago, but I don't think I was involved in the decision why. @SebastianZimmeck Do you remember why we got rid of it? It seems as though removing it broke our export domainlist functionality.

**Comment by SebastianZimmeck** [comment]
I do not remember why we removed it. Does the version history give a hint? It should be possible to find the context in which we made this change. 

Also, maybe, @kalicki1 remembers.

It could have just been a mistake that we incorrectly assumed we are no longer using it. If there are no reasons speaking against it, we can add it back in.
