### ISSUE TITLE
Fix header issue

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#299]
When stress testing a new DOM method, I found an error with our rules system that creates multiple rules for the same domain, breaking our header functionality when toggling on and off. Currently, I'm thinking of putting a check in the rule creator to see if a rule with that domain already exists.

**Comment by OliverWang13** [comment]
There are a few issues I am noticing here. For some reason, when I load the extension it loads with some rules in place for `global-privacy-control.glitch.me`. This can be solved by deleting our dynamic rules on load, but then a helper function should be in place to rebuild the desired rules. Another issue I am seeing is that sometimes the incorrect rule is deleted.

I find it odd that these issues were not found earlier. There might be a chance that work in another branch is somehow impacting other branches I travel to (perhaps through chrome caching?). I have tried to clear caches to remove this variable but it does not seem to perform differently. I have ran into other strange errors along this process like `npm run start` not loading the most recent version of the code, but that may be unrelated.

**Comment by SebastianZimmeck** [comment]
> I find it odd that these issues were not found earlier. 

It is well possible that there are bugs in the code that we introduced quite a while ago. So, it is good that you point them out. If appropriate, please open new issues on those.

**Comment by OliverWang13** [comment]
This issue had NOT existed before and had instead been caused by a small mistake I made. It is resolved so this issue will be closed.
