### ISSUE TITLE
Fix "Enable" button on Settings page

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#309]
When you click the "Enable" button on the main settings page of the extension it should send the "Do Not Sell" to every website on the domain list, regardless if the user has marked it to send the signal or not. Right now the extension still abides by whatever the user has set the domains to, which is the same functionality as the "Domain List" button on the main settings page. We need to fix the Enable button to send the signal no matter what.

This was found in going through the checklist in #289 for Chrome.

**Comment by OliverWang13** [comment]
This is resolved.
