### ISSUE TITLE
Fix "Website Response" dropdown on Popup

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#311]
In the popup, there is a dropdown that says "Website response". This dropdown should say whether or not the .well-known is present but is currently blank no matter if it is present or not.

This was found in going through the checklist in #289 for Chrome.

**Comment by OliverWang13** [comment]
The problem here is that our `wellknown` object was a global variable that can no longer function in mv3. We just need to find a way to get `wellknown[tabId]` to `dataToPopup()`.

**Comment by OliverWang13** [comment]
This has been resolved.
