### ISSUE TITLE
Fix cookie functionality

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#322]
Another issue I have spotted is that we are having some trouble placing cookies on Chrome.

**Comment by SebastianZimmeck** [comment]
These issues relate to first or third party cookies (i.e., our own extension cookies or the DAA opt out cookies, for example)? [Google is phasing out third party cookies, however, only by 2023](https://www.theverge.com/2021/6/24/22547339/google-chrome-cookiepocalypse-delayed-2023). So, maybe the issues are mv3 related?

**Comment by OliverWang13** [comment]
It is a problem with our first-party cookies.

**Comment by OliverWang13** [comment]
This is resolved.
