### ISSUE TITLE
Grey out dark mode toggle when disabled

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#329]
When the extension is disabled, the user cannot use any features on the popup. Currently, it appears as if you could toggle the dark mode on and off. The greying out of the popup when disabled should be extended to cover the dark mode toggle.

**Comment by SebastianZimmeck** [comment]
@Jocelyn0830 will take the lead here with assistance from @sophieeng.

**Comment by Jocelyn0830** [comment]
This should be resolved.
