### ISSUE TITLE
Post-merge codebase refactoring

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-optmeowt#330]
I will go through the codebase to remove any useless lines. This issue should be done pretty quickly. It is open mostly for merging purpose.

**Comment by SebastianZimmeck** [comment]
@Jocelyn0830, this is just some remaining clean-up work that you discovered and that was not already covered in the original refactoring issue #283?

**Comment by Jocelyn0830** [comment]
> @Jocelyn0830, this is just some remaining clean-up work that you discovered and that was not already covered in the original refactoring issue #283?

Oliver told me there could be some remaining console.logs he put in. My primary goal is going to remove those. I will also check if there is anything more that I can delete.
