### ISSUE TITLE
Check if the Wiki is up to date and update if necessary

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#337]
As the title says. Here is the [Wiki](https://github.com/privacy-tech-lab/gpc-optmeowt/wiki).

**Comment by OliverWang13** [comment]
The wiki still looks up to date (unless we want to expand on our developer explanations section). If we wanted to, we could briefly talk about how we set our header and dom signals.

**Comment by OliverWang13** [comment]
Let me know your thoughts, @SebastianZimmeck.

**Comment by SebastianZimmeck** [comment]
Yes, that is a good idea! So, feel free to include a few sentences, @OliverWang13.

**Comment by OliverWang13** [comment]
I added some information on the headers and DOM signal, and will close this issue.
