### ISSUE TITLE
Update store listing screenshots

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#338]
Our sreenshots for the store listings are outdated. @sophieeng, can you produce five new ones? Here are the specifications for the Chrome Web Store.

<img width="656" alt="Screen Shot 2022-07-21 at 11 08 12 AM" src="https://user-images.githubusercontent.com/11034003/180249109-4fac614c-dcd4-485d-875a-8c02040754d6.png">

I am not sure about the Firefox Store. Feel free to do everything on your own on the Firefox Store. I can put the screenshots up on the Chrome Web Store.

You can delete all unused assets and  put the new ones [in there](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/main/src/assets/chrome-web-store-assets). (Also, the naming of the folder strikes me as wrong; better `chrome-and-firefox-store-assets` or something like that; please make sure nothing breaks when renaming in case we are using these assets anywhere else).

**Comment by SebastianZimmeck** [comment]
Of course, let's omit the study code in the screenshots. That is just temporary.

**Comment by sophieeng** [comment]
The new files are in the new folder in assets called[ Chrome-Firefox-Store-Assets](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/main/src/assets/chrome-firefox-store-assets). The only changed images were screenshot-3, screenshot-4, and screenshot-5.

@SebastianZimmeck the new images for chrome have chrome added at the end of their image name. I will replace the ones on the Firefox store.

**Comment by sophieeng** [comment]
The new image changes have been uploaded to the Firefox store.

**Comment by SebastianZimmeck** [comment]
I changed the images on the Chrome Web Store.
