### ISSUE TITLE
Why is the extension icon behaving differently depending on the URL?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#340]
As the title says. Not sure, is this a bug?

For example, on https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo/ 
and 
https://github.com/privacy-tech-lab/gpc-optmeowt/

I am getting:

<img width="37" alt="Screen Shot 2022-07-21 at 4 33 00 PM" src="https://user-images.githubusercontent.com/11034003/180310104-2ef85dba-abd0-449b-a991-003a5361e59b.png">

But on other sites, e.g.,

https://dl.acm.org/doi/pdf/10.1145/3319535.3354212

as it should be:

<img width="49" alt="Screen Shot 2022-07-21 at 4 34 01 PM" src="https://user-images.githubusercontent.com/11034003/180310222-467ae8a1-b1db-419b-91b2-c802a30e7afc.png">

What is the reason for this difference? Is this a bug?

@sophieeng, can you look into this?

**Comment by SebastianZimmeck** [comment]
I am using Brave in the most recent version.

**Comment by SebastianZimmeck** [comment]
Also, is this purely a UI issue or are GPC signals not being sent?

**Comment by OliverWang13** [comment]
I looked into this and I think it is because of their individual content policies. These sites do not allow us to set the GPC signal, so the icon is correctly displaying that. This is acceptable behavior for the icon, in my opinion.

**Comment by SebastianZimmeck** [comment]
The reason is the Content Security Policy (#252)?

**Comment by OliverWang13** [comment]
I added this to our wiki well-known, and will be closing this issue.
