### ISSUE TITLE
Clean up asset folder

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#342]
It seems to me that the asset folder is outdated. I don't actually know what is what. @sophieeng, could you check for every item whether we actually currently use it (in the extension, readme, store listing, elsewhere), and delete those items we do not use. 

I already removed the Privacy Without Compromise screenshot from the repo and the Firefox Store because that landing page no longer exists.

**Comment by Jocelyn0830** [comment]
I created a new branch and deleted useless items. The extension is still working properly. I am not sure how I can check the store listing. 'OptMeowt_Chrome_Web_Store.psd' seems to be something that we use in the store listing, so I did not delete it. It is also possible that I might delete items that are used in the store listing.

**Comment by SebastianZimmeck** [comment]
Here is what is used in the Chrome Web Store.

<img width="660" alt="Screen Shot 2022-08-02 at 5 59 34 PM" src="https://user-images.githubusercontent.com/11034003/182481019-9da2af47-f98d-4e17-8328-5d631ac8bef4.png">

So, it does not look like it is used there. 'OptMeowt_Chrome_Web_Store.psd' is a Photoshop file, probably, more for the icon.png. So, let's rename it to icon.psd in  case anyone wants to modify the icon going forward. 

Also, if you could make sure that nothing breaks in the readme. Because we have some assets in there as well.

Then, feel free to merge.

**Comment by Jocelyn0830** [comment]
Actually Sophie updated [chrome-firefox-store-assets](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/main/src/assets/chrome-firefox-store-assets) very recently. The store listing asset folder should be fine. 

Everything looks fine now after cleaning. I am closing this.
