### ISSUE TITLE
Fix exported analysis csv not containing complete analysis results

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#348]
When I performed the analysis of 40+ websites over two days and exported the analysis results, I realized that my later exports did not contain (all) the results from previous exports. Mostly, in only contained new analysis results. However, this does not seem to be the case for the list that is displayed in the settings. That list was complete. I disabled and enabled OptMeowt multiple times during the process, closed the browser, etc. It would be good if someone can look into replicating this potential bug.

**Comment by Jocelyn0830** [comment]
I am not able to replicate this problem on my end. I tested 45 sites by hand. The 45 sites are in the Analysis List, and there are exactly 45 sites in the exported analysis data csv. 
I did another testing using the crawler. There are 54 sites in the Analysis List, and also 54 in the exported csv.

**Comment by SebastianZimmeck** [comment]
What happens if you do the following?

1. Go to a website A and do an analysis
2. Click on the Download button in the popup
3. Disable OptMeow in the Firefox settings per below
4. Enable it, go to another website B, and do an analysis
5. Click on the Download button in the popup

<img width="1046" alt="Screen Shot 2022-08-07 at 10 27 29 AM" src="https://user-images.githubusercontent.com/11034003/183295820-ee27c6b8-a426-47ff-9a27-a0caa1b3f657.png">

I see only see the analysis results for website B in the second downloaded csv. However, in the analysis list I see both sites A and B.

Also, when I do an analysis, download the csv, close the browser, and download the csv again, I am not seeing the analyzed site in the csv anymore. Because one could not rely on permanent storage for exporting purposes.

If that's how it is, it does not necessarily need to be fixed. However, it should be mentioned as a Known Issue/Quirk.

**Comment by Jocelyn0830** [comment]
> I see only see the analysis results for website B in the second downloaded csv. However, in the analysis list I see both sites A and B.
> 
> Also, when I do an analysis, download the csv, close the browser, reopen the browser, and download the csv again, I am not seeing the analyzed site in the csv anymore.
> 
> If that's how it is, it does not necessarily need to be fixed. However, it should be mentioned as a Known Issue/Quirk. Because one could not rely on permanent storage for exporting purposes.

I tested, and It is also the case on my end.

**Comment by SebastianZimmeck** [comment]
OK, I think it is OK as is, but that should be explained in the Wiki.

**Comment by SebastianZimmeck** [comment]
I am thinking now this should be fixed long-term.

**Comment by SebastianZimmeck** [comment]
As discussed, this issue also relates to how analysis results are recorded when doing an analysis crawl. The easiest is to use the extension functionality to also record the crawl results (as opposed to having additional crawl functionality).

(Also, after doing a quick check, it does not look like the lack of persistence of analysis results is due to the use of the `sessionStorage` API, which does not seem to be used throughout the codebase. So, the reason must be something else.)

**Comment by OliverWang13** [comment]
I believe that this is an issue with us exporting a local variable instead of a database object, so hopefully it can be a quick fix.

**Comment by SebastianZimmeck** [comment]
As just discussed, @sophieeng will take care of this.

**Comment by Jocelyn0830** [comment]
This should be fixed now.
