### ISSUE TITLE
Create OptMeowt demo video

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#349]
It would be nice to create a video for YouTube for OptMeowt similarly to [Raf's video on PrivacyFlash Pro](https://github.com/privacy-tech-lab/privacyflash-pro#2-demo-video).

**Comment by SebastianZimmeck** [comment]
I thought about this again. It is probably the easiest to use a computer on campus, for example, in the Exley Science library for video editing if needed. Since this is a one-off task we may be able to make do with that. If not, maybe some of these [alternatives](https://www.cinecom.net/post-production/7-adobe-premiere-pro-alternatives/) will work.

I do not have suggestions for a free screencast tool, but maybe Zoom will do.

Also, this Wednesday I will put an external microphone in the CS Lab since the sound is sometimes a bit dull with built-in microphones.

**Comment by SebastianZimmeck** [comment]
@sophieeng will make the volume a bit more uniform, and then we should be done.

**Comment by sophieeng** [comment]
The volume has been updated and the video has been re-uploaded to the GPC Web promo folder. I will wait for @SebastianZimmeck to give it a final check and close the issue.

**Comment by SebastianZimmeck** [comment]
Nice job, @sophieeng! I added the video to the readme and our [site](https://www.privacytechlab.org/). Feel free to close this issue.
