### ISSUE TITLE
Check if protection mode is working on arstechnica.com; if not, fix

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#353]
When I visit arstechnica.com with protection mode enabled, it seems that we are not re-writing the US Privacy String. There is no `Y` in the third position. It looks like it should work because the extension icon indicates a green circle. There is no difference when I enable or disable ad blocking. I am using the most recent version of Brave.

<img width="560" alt="Screen Shot 2022-08-12 at 8 52 14 PM" src="https://user-images.githubusercontent.com/11034003/184461259-cdb8474c-26a9-40d0-9261-ad6e0f50c60b.png">

(This can wait until we are done with the crawl issues; @OliverWang13, I assigned you for the time being but feel free to re-assign and anyone can pick this up too.)

**Comment by SebastianZimmeck** [comment]
As discussed today, @Jocelyn0830 will check if she can replicate the problem. Then, maybe, take ten or so other sites and do a random spotcheck if there are more sites where this problem exists. Also, it would be useful to check if the USPAPI has the same `1---` result for sites that implement both the cookie and USPAPI version of the US Privacy String.

**Comment by Jocelyn0830** [comment]
I am able to replicate the problem on my end. I enabled Protection Mode and the ground truth of USPAPI on arstechnica.com is 1---.

Below is a spotcheck of 10 sites that have 
- [x] https://www.brusselstimes.com/
- [x] https://careersidekick.com/
- [x] https://www.nuernberg.de/internet/stadtportal/index.html
- [x] https://digital.nhs.uk/
- [x] https://www.feratel.at/
- [ ] https://www.freep.com/ (USP cookie is 1---)
- [x] https://healthhabitsdaily.com/
- [x] https://www.iatropedia.gr/
- [x] https://www.baden-baden.de/
- [x] https://howtofixit.net/

The spotchecking results reveal that the protection mode is working properly on the majority of sites.

**Comment by Jocelyn0830** [comment]
After taking a closer look, I suspect that our extension cannot rewrite the USP cookie value if the site implements the USP cookie itself. 

My methodology for spotchecking:
1. Make sure LA vpn is disabled.
2.  Disable the protection mode. 
3. Load the site, check the ground truth of USP cookie. 
4.Enable the protection mode, and check the ground truth of USP cookie again. 
5. Record whether the cookie is updated.
6. Clear the cookie data. Enable the LA vpn. Repeat step 2-5. 

Here is a spotcheck following the above methodology (Note that all the sites below have USPS cookie implemented):
- [ ] [arstechnica.com](https://arstechnica.com/)
- [ ] https://www.urbandictionary.com
- [x] https://thehill.com/ 
no vpn: USP cookie 1---, not updated
with vpn: USP cookie not 1---, updated
- [x] https://www.cheatsheet.com/ (USP cookie updated with vpn on)
no vpn: USP cookie not 1---, updated
with vpn: USP cookie not 1---, updated
- [x] https://www.sciencealert.com/
no vpn: USP cookie not 1---, updated
with vpn: USP cookie not 1---, updated
- [x] https://www.rollingstone.com/
no vpn: USP cookie 1---, not updated
with vpn: USP cookie not 1---, updated
- [x] https://variety.com/
no vpn: USP cookie 1---, not updated
with vpn: USP cookie not 1---, updated
- [ ] https://www.whiskeyriff.com/
no vpn: USP cookie 1---, not updated
with vpn: USP cookie 1---, not updated
- [ ] https://www.bonappetit.com/
no vpn: USP cookie 1---, not updated
with vpn: USP cookie 1YYN, no need to be updated, ignore
- [ ] https://www.edmunds.com/
no vpn: USP cookie not 1---, updated
with vpn: USP cookie not 1---, updated

So it seems that our extension is not able to rewrite the USP cookie value if the site implement the USP cookie value 1---.

**Comment by Jocelyn0830** [comment]
This should be resolved.

**Comment by SebastianZimmeck** [comment]
Nice work, @Jocelyn0830!
