### ISSUE TITLE
Remove code that generates redundant data in exported csv file

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-optmeowt#354]
There too many columns in the Analysis Mode's exported csv file. We should delete the useless ones.

**Comment by SebastianZimmeck** [comment]
I.e., remove the logic in the code that generates this data.

**Comment by Jocelyn0830** [comment]
I removed the useless columns (mostly timestamps) from the exported csv file.

**Comment by Jocelyn0830** [comment]
This should be resolved.
