### ISSUE TITLE
Write USP cookie and USP API 1YYY for all sites

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-optmeowt#362]
As discussed, I will first look into whether we want to rewrite USP cookie as 1YYY for all sites.

**Comment by SebastianZimmeck** [comment]
This would also relate to both the cookie and USP API values.

My general thinking at the moment is to not mess with a string value (except rewriting the third character to `Y`, of course) unless there is no string or the value is `1---`.

**Comment by SebastianZimmeck** [comment]
And once we settled on how we rewrite the Strings, let's add that information to the readme because it goes to the core question of how effective the opt out will be.

**Comment by Jocelyn0830** [comment]
Now we write 1YYY if the website has 1--- implemented. If the sites have other USPS values, we rewrite the third character to Y.
