### ISSUE TITLE
Fix analysis mode exporting two csv files upon clicking

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-optmeowt#363]
Now when we download the exported csv file either from popup or settings page, the extension automatically downloads two copies. I traced back to the previous commits, and this issue occurs after I fixed Issue-#348.

**Comment by Jocelyn0830** [comment]
This should be fixed now.

**Comment by SebastianZimmeck** [comment]
Currently, the export works fine when done from the popup but there seems to be some flakiness when done from the settings page. @katehausladen will first check to replicate the problem. Then, depending on the result, look for a fix. In particular, what is the difference between popup and settings that makes one work but not the other.

**Comment by Jocelyn0830** [comment]
A detailed guide for replicating the problem:
1. Move to the branch issue-363. Build the project on this branch. 
2. Clear all the cookies data from the Firefox settings page. 
3. Load the extension at about:debugging.
4. Open the extension's settings page and change to analysis mode.
5. Navigate to https://www.washingtonpost.com/. Run analysis and stop analysis.
6. Open the extension's settings page. Click on "exporting analysis data". Check if the extension downloads two copies of csv files.

@sophieeng, feel free to provide more details.

**Comment by katehausladen** [comment]
I followed Jocelyn's instruction to replicate the problem and could not replicate it. It downloaded 1 .csv file with the correct data from the settings page. It also worked correctly from the popup.
