### ISSUE TITLE
Fix third party domain list in popup

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#364]
It seems that the popup does not show any third party domains anymore. This seems to be the case for any site I visit. For example, below the issue is shown for [The Atlantic](https://www.theatlantic.com/).

<img width="1105" alt="Screen Shot 2022-09-10 at 10 51 26 PM" src="https://user-images.githubusercontent.com/11034003/189510290-25167256-06a5-484d-97e0-e1d3b267817c.png">

I tried with the most recent Brave and Chrome versions.

We should also check if this is purely an issue with the popup or if nothing is recorded in the domain list either.

**Comment by SebastianZimmeck** [comment]
I tried again on Google Chrome. The problem is different this time. It seems I am seeing (third party) domains for all sites I ever visited. For example, below I visited arstechnica.com and then visited spiegel.de. When I am on the latter site, the popup still shows domains related to arstechnica.com.

So, the bottom line is, the third party domains are unreliable.

<img width="1200" alt="Screen Shot 2022-09-11 at 9 41 38 AM" src="https://user-images.githubusercontent.com/11034003/189530760-a21f549a-b758-4f4c-92b6-c5147552dfd7.png">

**Comment by Jocelyn0830** [comment]
I failed to replicate this problem on my end. I used the current main branch to build the project.
For me, the popup showed third party domains of [The Atlantic](https://www.theatlantic.com/). I also visited arstechnica.com and then visited spiegel.de, things still worked fine. 

<img width="1329" alt="Screen Shot 2022-09-14 at 15 34 13" src="https://user-images.githubusercontent.com/102534933/190246400-ea76ba27-655d-4546-9701-fefa3c3bd965.png">

As the screenshot shows, the list of third party domains of spiegel.de doesn't include arstechnica.com.

**Comment by SebastianZimmeck** [comment]
Thanks, @Jocelyn0830! It could be that I see this problem on my end because I have 7,000+ domain list entries. Maybe, that is too much. If both @sophieeng and @katehausladen cannot replicate this either, I'd chalk it up as specific problem that we do not need to address.

**Comment by katehausladen** [comment]
I am actually getting both issues. 1) if I haven't used optmeowt for a few minutes, it takes at least 1 minute for the different 3rd party domains to show up (regardless of the website/how many times you reload the page). It appears that this dropdown is in the "Second-to-load components" section in popup.js, so it is possible that the code is structured in a way that creates this delay (other essential things have to load first). 2) after the 3rd party domains do show up, then I get the second issue of showing 3rd party domains from multiple websites. This issue only seems to occur if I am loading multiple websites within the same tab. If I load the websites in separate tabs, the correct 3rd party domains are shown. It doesn't seem to matter whether the tabs are open at the same time or not, only that the websites are loaded in the same tab.

**Comment by Jocelyn0830** [comment]
> I am actually getting both issues. 1) if I haven't used optmeowt for a few minutes, it takes at least 1 minute for the different 3rd party domains to show up (regardless of the website/how many times you reload the page). It appears that this dropdown is in the "Second-to-load components" section in popup.js, so it is possible that the code is structured in a way that creates this delay (other essential things have to load first). 2) after the 3rd party domains do show up, then I get the second issue of showing 3rd party domains from multiple websites. This issue only seems to occur if I am loading multiple websites within the same tab. If I load the websites in separate tabs, the correct 3rd party domains are shown. It doesn't seem to matter whether the tabs are open at the same time or not, only that the websites are loaded in the same tab.

I was working with Kate and I was able to replicate the issue following Kate's procedure.

I traced back to previous commits and the problem existed when we published the latest release.

**Comment by SebastianZimmeck** [comment]
Excellent! Nice work, @katehausladen and @Jocelyn0830.

**Comment by SebastianZimmeck** [comment]
@katehausladen will look a bit more into this issue using a set of 20 random sites or so.

- How many of these display no third party domains in the popup?
- How many have wrong third part domains in the popup?
- Is this functionality-related or just UI? For example, is the GPC status of third party sites incorrectly displayed dependent on the status of the current site? That should not be the case. Those third party sites should be dependent on the previous site.
- Look a little bit into the DB logic and find out where this problem could stem from.

**Comment by SebastianZimmeck** [comment]
@katehausladen, when you see the icon like this

<img width="39" alt="Screen Shot 2022-09-20 at 6 34 23 PM" src="https://user-images.githubusercontent.com/11034003/191376913-4ad5a76d-3e0d-4811-a2d1-6f01c5cb3c1a.png">

and not like this

<img width="41" alt="Screen Shot 2022-09-20 at 6 34 36 PM" src="https://user-images.githubusercontent.com/11034003/191376932-fc48b633-5d39-4781-8cfd-6bdbc42acc3e.png">

try restarting your browser. 

The green circle means "GPC signal sent" and that seems a bit flaky too. It is a different issue, but could also affect your testing.

**Comment by katehausladen** [comment]
I changed the code in protection.js and protection-ff.js so that now the 3rd parties are being added to an object that stores all the 3rd parties for that domain as the domain list is being updated. For instance, if the current domain is nytimes.com, any site that is processed while nytimes.com is the current domain is added to a list of values {nytimes.com: {all the 3rd parties, added when they are processed by updateDomainlist} }. This correctly identifies any sites that are being loaded for any given current domain. The only problem is sometimes the previous site (only the domain itself, no 3rd parties) is loaded after the new site has been loaded. For instance, I loaded theatlantic.com and then loaded washingtonpost.com in the same tab. As shown, after the new site (washingtonpost.com) is loaded, theatlantic.com is parsed again.
<img width="695" alt="Screen Shot 2022-10-04 at 11 31 34 AM" src="https://user-images.githubusercontent.com/40359590/193864741-784ca576-4260-450d-b3e6-8b489950aa2c.png">

**Comment by SebastianZimmeck** [comment]
@katehausladen, does that mean that your change essentially resolves the problem (except for the case of a previous site loading after the next)?

**Comment by katehausladen** [comment]
yes

**Comment by SebastianZimmeck** [comment]
OK, great! If you have not done so, please create a branch `issue-364` with your changes, open a PR with @sophieeng or @Jocelyn0830 as reviewer, and once merged, please close this issue.

**Comment by katehausladen** [comment]
fixed
