### ISSUE TITLE
Fix dark mode Firefox popup mode indicator

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#368]
When on Firefox, the popup has a label at the top detailing if it's in Analysis mode or Protection mode. This used to be a button to switch the mode before I moved that functionality to the main settings page. Now, it doesn't show any UI change if you hover over it in light mode, but there is still a reaction in dark mode. I'll remove that visual change.

**Comment by Jocelyn0830** [comment]
This should be fixed now.
