### ISSUE TITLE
Popup defaults to analysis mode when getCurrentParsedDomain function imported to protection.js

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-optmeowt#374]
When I import the getCurrentParsedDomain function from popup.js (into protection.js and protection-ff.js), the popup defaults to analysis mode in both chrome and firefox. The domain lists are empty, and the only buttons that work are "More" and "Tutorial." The popup works normally in both chrome and firefox if that function is copy pasted into both files and not imported.
<img width="1440" alt="Screen Shot 2022-10-07 at 2 31 06 PM" src="https://user-images.githubusercontent.com/40359590/194626403-2492d722-9cf8-4020-84fc-b6428abd092e.png">
<img width="1440" alt="Screen Shot 2022-10-07 at 2 19 19 PM" src="https://user-images.githubusercontent.com/40359590/194626412-5bbaeac3-3796-4d26-9240-445b655436dc.png">

**Comment by SebastianZimmeck** [comment]
This issue will be superseded by our plans of separating our program into a (a) protection mode extension and (b) analysis mode crawler. The extension will not longer contain the analysis mode.
