### ISSUE TITLE
Fix continuous integration

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#381]
See [here](https://github.com/privacy-tech-lab/gpc-optmeowt/actions/runs/3419595320).

> Node.js CI: Some jobs were not successful

It looks like the continuous integration is failing. We first need to solve #365, #375, #377. Then we can take on this issue.

**Comment by sophieeng** [comment]
Now that the Mocha tests in issue #375 have been merged in main. The continuous integration should now be working. See example #387 for a PR that passes checks.
