### ISSUE TITLE
Test extension (given removal of analysis mode) and prepare new release

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#382]
As discussed, let's all install OptMeowt from the #379 branch and test how it goes. These are informal tests. Once we have unit testing and continuous integration in place, we can be more systematic and come up with a more comprehensive unit test suite (if we want and have time).

**Comment by SebastianZimmeck** [comment]
Once the test suite is finished (#392), we test and create a new release (this issue).

**Comment by sophieeng** [comment]
I ran `npm test` on the newest version of the main branch and all tests passed. I also ran through the manual UI testing instructions on both Firefox and Chrome and both passed. One thing to note is that people may not have Puppeteer installed so if `npm test` fails, run `npm install`.

**Comment by SebastianZimmeck** [comment]
OK, @sophieeng, could you modify the readme and include/modify install instructions for the test as necessary?

**Comment by sophieeng** [comment]
Yes @SebastianZimmeck I just opened issue #404 for it that I will finish for the meeting.

**Comment by OliverWang13** [comment]
The release has been created on Github, so I will be closing this.
