### ISSUE TITLE
Determine webpack version and possibly upgrade

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#383]
In our discussion the question came up which version of webpack we are using. For example, in PP we had [various issues moving from v3 to v4](https://github.com/privacy-tech-lab/privacy-pioneer/pull/420). So, which version of webpack are we using? If we are using v3, we should move to v4. If we are on v4, it is probably the best to first establish the testing framework and then tackle the build process (and change the test framework again, if necessary).

**Comment by sophieeng** [comment]
Our current webpack version: 5.53.0
Most current webpack version: 5.75.0

**Comment by SebastianZimmeck** [comment]
OK, so we are on version 5. As far as I am concerned, this can stay as is.
