### ISSUE TITLE
Writing a mocha test based on Sophie's instructions 

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-optmeowt#391]
Writing a mocha test using Sophie's instructions (here: https://docs.google.com/document/d/1VLOrDEHGk6IjsAFhKJLNKnE2C8vE16fYW8vIKhHA8dg/edit), which will eventually be added to the readme. This is a separate from issue #365 because she was testing Jest in that issue.

**Comment by sophieeng** [comment]
We need to make sure this test is properly nested in its subdirectory before we close the issue.

**Comment by sophieeng** [comment]
The test is merged, see ../test/background/makeCookieIAB.test.js
