### ISSUE TITLE
Testing a new test framework: Jasmine and Puppeteer

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#401]
Like Oliver mentioned in issue #392, DuckDuckGo was able to test the core functionality of GPC that we have not been able to achieve. I'm interested in using their test environment to understand what differences there are particularly between Mocha and Jasmine that may be stopping us from getting a working test. DDG also uses Puppeteer which I'd like to see how it works with testing.

**Comment by SebastianZimmeck** [comment]
OK, sounds good, @sophieeng! Once you know, please make a call together with @OliverWang13 on which unit test framework we use.
