### ISSUE TITLE
Check over Architecture ReadMe

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#408]
This should be the last thing we do before releasing, to ensure everything looks as desired.

**Comment by OliverWang13** [comment]
Additionally, update the method of adding and removing the dom signal, if that is included in the architecture ReadMe

**Comment by SebastianZimmeck** [comment]
> Additionally, update the method of adding and removing the dom signal, if that is included in the architecture ReadMe

That would be good. And also check if there is other documentation that needs to be updated in that regard, e.g., code comments, wiki, ...

**Comment by OliverWang13** [comment]
This looks good, so I will be closing this issue.
