### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#413]
It seems that there is at least one dependency that should be removed from the [package.json](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/main/package.json) (which is Puppeteer). Let's take this opportunity to take critical look and remove all unused dependencies (and fix any other dependency issue should we come across one).

**Comment by SebastianZimmeck** [comment]
I realize that we use Puppeteer for testing. Still, let's take a look at the dependencies.

**Comment by OliverWang13** [comment]
@sophieeng and I went through and removed all the ones that were obviously unused. We can do a deeper search just in case, but we are fairly confident we got most of them.

**Comment by SebastianZimmeck** [comment]
Once done, @OliverWang13 and @sophieeng will merge, see if all tests pass, and manually check that OptMeowt still works, and we should be done.

**Comment by OliverWang13** [comment]
This is pushed and should be resolved.
