### ISSUE TITLE
Update readme and Wiki as necessary, especially, adapt analysis mode and protection mode explanation

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#414]
We currently do not have an explanation.

**Comment by OliverWang13** [comment]
Additionally, we should update the permissions section as it is slightly out of date.

**Comment by SebastianZimmeck** [comment]
This should also include the Wiki.

**Comment by OliverWang13** [comment]
I cleaned up our ReadMe a bit, should be looking alright now.
