### ISSUE TITLE
Update store listings and promo video as necessary

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#416]
- Are the Firefox and Chrome store listings up to date? Do we need to upload new [screenshots](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/main/src/assets/chrome-firefox-store-assets) or update the descriptions there? If so, let's do that. We can delete all the old screenshots that we no longer use from the repo.
- Also, is the promo video up to date? It is not worth it to go to great length, but if there is outdated functionality described (especially, the analysis mode), that should be removed.

**Comment by sophieeng** [comment]
New video is uploaded named "GPC Promo Video" in the Promo_Materials of GPC_Web folder in the shared drive. The old one I renamed but left it in the folder because I wasn't sure if I should deleted.

**Comment by SebastianZimmeck** [comment]
> New video is uploaded named "GPC Promo Video" in the Promo_Materials of GPC_Web folder in the shared drive. 

If you have not done so yet, @sophieeng, it would be good to update the link in the readme to the new promo video.

> The old one I renamed but left it in the folder because I wasn't sure if I should deleted.

As far as I am concerned, we can delete it. It will remain in version control if we ever need it.

**Comment by sophieeng** [comment]
I have replaced the link and deleted the old video version. This is complete.
