### ISSUE TITLE
In Chrome the button to turn Do Not Sell button does not appear to consistently turn off `navigator.globalPrivacyControl` 

### ISSUE THREAD

**Issue by AramZS** [privacy-tech-lab/gpc-optmeowt#419]
Tested on Chrome and Chrome Canary and deactivating GPC does not appear to work on the latest version of the extension.

**Comment by SebastianZimmeck** [comment]
@OliverWang13 will inquire further.

**Comment by SebastianZimmeck** [comment]
Closing this issue as we are not able to replicate it. Feel free to reopen, @AramZS.
