### ISSUE TITLE
Update opt out link detection

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#422]
We need to update the Do Not Sell link detection. Two points:

- **Expand the regex**: As @katehausladen [was saying](https://github.com/privacy-tech-lab/gpc-web-crawler/issues/42#issuecomment-1550562460):

   > 10/40 The link is now named some iteration of "Your Privacy Choices"/"Your Privacy Options"/"Manage Your Privacy Choices." If this terminology is accepted as equivalent to a DNSL, we should expand the regular expression to include variations of this. 

   Expansion of the regex should also include "Limit the Use of My Sensitive Personal Information" links (see below).

- **Detect icon or icon text (the latter via regex)**: There is now an [official Do Not Sell icon and accompanying text]((https://oag.ca.gov/privacy/ccpa/icons-download)) sanctioned by the California regulator. So, let's check if we can search for the [icon and/or icon text].

These changes are based on the [new (and final CCPA) regulations](https://cppa.ca.gov/regulations/pdf/cppa_regs.pdf):

> § 7015. Alternative Opt-out Link.
> 
> (a) The purpose of the Alternative Opt-out Link is to provide businesses the option of providing consumers with a single, clearly-labeled link that allows consumers to easily exercise both their right to opt-out of sale/sharing and right to limit, instead of posting the two separate “Do Not Sell or Share My Personal Information” and “Limit the Use of My Sensitive Personal Information” links. The Alternative Opt-out Link shall direct the consumer to a webpage that informs them of both their right to opt-out of sale/sharing and right to limit and provides them with the opportunity to exercise both rights.
> 
> (b) A business that chooses to use an Alternative Opt-out Link shall title the link, “Your Privacy Choices,” or, “Your California Privacy Choices,” and shall include the following opt-out icon adjacent to the title. The link shall be a conspicuous link that complies with section 7003, subsections (c) and (d), and is located at either the header or footer of the business’s internet homepage(s). The icon shall be approximately the same size as other icons used by the business in the header or footer of its webpage.
> 
> (c) The Alternative Opt-out Link shall direct the consumer to a webpage that includes the following information:
> (1) A description of the consumer’s right to opt-out of sale/sharing and right to limit, which shall comply with section 7003, subsections (a) and (b); and 
> (2) The interactive form or mechanism by which the consumer can submit their request to opt-out of sale/sharing and their right to limit online. The method shall be easy for consumers to execute, shall require minimal steps, and shall comply with section 7004.

Here is how the icon looks (as developed by Lorrie Cranor and her team as we heard in the Shasha Seminar):

<img width="88" alt="Screenshot 2023-05-20 at 5 46 25 PM" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/11034003/ac18a8ef-6862-40f4-ae63-3bdda67880a8">

@OliverWang13 will take the lead on this with the help of @sophieeng.

**Comment by OliverWang13** [comment]
I have created a branch (422) in the crawler repo and changed the regex to include the following

Your Privacy Choices
Your Privacy Options
Manage Your Privacy Choices
Limit the Use of My Sensitive Personal Information
Your California Privacy Choices

As well as a few other possible combinations. @katehausladen, do you know some sites that use these phrasings so I can test the new regex?

**Comment by OliverWang13** [comment]
I uploaded the changed regex but for this change to take effect we still need to repackage the extension as an xpi file for the crawler to load.

**Comment by OliverWang13** [comment]
I changed the regex and created the xpi file, and tests show that the regex is able to capture a lot more now. This issue should be resolved, so I will be closing it.
