### ISSUE TITLE
Possibly refactor nested code 

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#425]
As @katehausladen [found out for our crawler](https://github.com/privacy-tech-lab/gpc-web-crawler/issues/50#issuecomment-1611998479), some analysis code there was convoluted such that the crawler ran much slower than it could. The question is if this code also exists in OptMeowt. If it does, it should be refactored in the same way. If not, we can leave the code as is and close this issue straight.

**Comment by katehausladen** [comment]
The nested functions in the analysis extension were in analysis.js, which doesn't exist in OptMeowt. I checked protection.js and protection-ff.js (OptMeowt's equivalent of analysis.js), and I did not find any nested functions.
