### ISSUE TITLE
Check if OptMeowt meets accessibility standards

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-optmeowt#430]
As @SebastianZimmeck mentioned in Teams, we need to make sure that OptMeowt meets accessibility standards. For websites, you use [this](https://chrome.google.com/webstore/detail/siteimprove-accessibility/djcglbmbegflehmbfleechkjhmedcopn), but it may be different for browser extensions. We may be able to just load the [UI's html](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/main/src/popup/popup.html) in the browser.

**Comment by Jocelyn0830** [comment]
Most extensions and chrome's built in lighthouse only checks https or http. I'm not sure if it worths converting our extension into a web application. So, instead, I found an [online checker](https://websiteaccessibilitychecker.com/checker/index.php) that could check if html meets accessibility standards and uploaded the [UI's html](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/main/src/popup/popup.html) into it. At least the result can serve as a reference. 

Attached are results and I'll look more into it.
<img width="1147" alt="Screen Shot 2023-10-16 at 19 47 52" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/102534933/d0589e4b-0b30-4e73-aaf9-a7010aa2251f">
<img width="1135" alt="Screen Shot 2023-10-16 at 19 48 05" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/102534933/50e8f01c-0b3c-4c40-939e-10cf291d7801">

**Comment by SebastianZimmeck** [comment]
OK, we should fix at least the "Known Problems."
