### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#446]
Following the closing of issue #442, create a new release and ship it to Firefox and Chrome.

**Comment by OliverWang13** [comment]
I might hold off on this for a second while we decide how to resolve #447, just in case we wish to implement a popup or disclaimer.

**Comment by OliverWang13** [comment]
I uploaded a few more screenshots that I used and removed outdated ones. This should be dealt with so I will close the issue.

**Comment by SebastianZimmeck** [comment]
v4.3.1 is also published in the Chrome Web Store.
