### ISSUE TITLE
Update ReadME Contributors

### ISSUE THREAD

**Issue by sophieeng** [privacy-tech-lab/gpc-optmeowt#450]
<img width="838" alt="Screenshot 2024-01-16 at 8 13 23 PM" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/101224170/c22bdcfe-83f9-46bc-b449-57ec0cad7bdf">

On line 30 of our ReadMe (`README.md`), we list the contributors, past and present, of this extension. See above photo as reference. 

This is a little out of date. Jocelyn Wang should be moved to the line for previous contributors and Francisca and Matt should be moved to the current contributors. 

We list people by date they joined the lab so Francisca and Matt's information should go after Kate's. Jocelyn can be moved to the front of the previous contributors because she's most recently left the lab. Please keep the same format of `First_Name Last_Name (@Username)`.

@franciscawijaya I'll let you take care of this so you can practice your GitHub skills. Let me know if you have any questions!

**Comment by SebastianZimmeck** [comment]
And if you could do this in an `issue-450` branch, open a PR, and add @sophieeng as a reviewer, @franciscawijaya.
