### ISSUE TITLE
Meet with newer lab members to get them comfortable with the codebase (design optmeowt curriculum?)

### ISSUE THREAD

**Issue by OliverWang13** [privacy-tech-lab/gpc-optmeowt#454]
It would be good to create a google doc or some sort of detailed record of how to explain how OptMeowt functions.

**Comment by OliverWang13** [comment]
Here is a link to the DOC I created to acquaint new members with OptMeowt: https://docs.google.com/document/d/1H0sA6hK0Q0OLT4Tz_Yp-byHi0U4Ue5DO8k7K-NXnY2Q/edit?usp=sharing

@franciscawijaya and @Mattm27, it would be great if you could skim it over and let me know of any revisions you may have. Much of it should be repeating what I already said in our previous meeting, but it would still be valuable to look over it again.

@sophieeng, if you could also skim that would be appreciated.

**Comment by Mattm27** [comment]
This looks great, @OliverWang13. Very detailed and the snippets of code included in the doc are also a huge help. No revisions I can think of right now on my end!

**Comment by Mattm27** [comment]
This looks great, @OliverWang13. Very detailed and the snippets of code included in the doc are also a huge help. No revisions I can think of right now on my end!

I am sure as we continue to discuss more issues/projects for optmeowt going forward, it will be helpful to add additional information as we see fit.

**Comment by OliverWang13** [comment]
The doc is now in the `GPC/GPC-Web/OptMeowt-Guide` in the shared drive

**Comment by franciscawijaya** [comment]
I really like the structure of the guide (divided into 7 different important questions). As someone who is still getting acquainted with Javascript and the codebase, this definitely helped me understand more about the codebase and less intimidated by the idea of working with the codebase. More importantly, it provides a great overview of maintaining Optmeowt, drawing attention to certain aspects of the codebase and concepts (such as keywords) that would be useful in the research process. I personally think this is a useful guide and start for new members like me! Thank you so much, @OliverWang13 !!

**Comment by OliverWang13** [comment]
Great! I will close this issue. When new members join the lab, we can point them towards the guide located at `GPC/GPC-Web/OptMeowt-Guide`.

**Comment by SebastianZimmeck** [comment]
Excellent, @OliverWang13!

Can you include a link to the guide in the readme? Feel free to open a new section if it does not fit into an existing one.

**Comment by OliverWang13** [comment]
Yes, I included it in section 3 of the readme.
