### ISSUE TITLE
Finish all open issues and hand over work before hiatus

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#459]
@sophieeng, as discussed, since you will be on hiatus after this semester, it would be good if you can check if there is anything open on your end, and hand over any open work. Especially, it would be good if you can explain to @Mattm27 and @franciscawijaya, the unit testing and continuous integration.

I am opening this issue here, but it also relates to the [crawler](https://github.com/privacy-tech-lab/gpc-web-crawler) or any  other repo you have worked on.

**Comment by SebastianZimmeck** [comment]
Not sure, for example, if the mv3 migration has any impact on the unit test suite or continuous integration. If so, we should address that before you leave (and if so, open a new issue for that).

**Comment by franciscawijaya** [comment]
Reread the repo (eg. unit tests) and meet with @sophieeng

**Comment by sophieeng** [comment]
The test suite seems to be running as expected in the CI ([GitHub actions](https://github.com/privacy-tech-lab/gpc-optmeowt/actions)) and locally. The READMe explanations also seem clear to me.

I finished adding explanations to the gpc.test.js test file. I believe the other tests in the other files are straightforward to understand. The gpc.test.js file was more complicated but should be accessible now. 

When I meet with Francisca and Matt later on this week, I'll walk them through all the test files in the test suite, as well as the manual UI tests. I'll add more comments to the test files and READMe as needed from whatever questions they have.

**Comment by SebastianZimmeck** [comment]
Sounds good, @sophieeng! 

> When I meet with Francisca and Matt later on this week,

@Mattm27 and @franciscawijaya, before you meet with @sophieeng, can you run  the tests on your end and make sure you know how to do the UI tests?

**Comment by sophieeng** [comment]
I've met with Francisca and Matt to explain the repo + test suite. All the tests are working as expected. Don't hesitate to reach out if you have any questions about them in the future! This issue is complete.
