### ISSUE TITLE
Check for the green ring and fix

### ISSUE THREAD

**Issue by franciscawijaya** [privacy-tech-lab/gpc-optmeowt#460]
Reference: similar to issue #340 

Action plan: 
- take a fresh browser (both chrome and firefox) and install the extension
- pick 100 random sites from the sample (in the crawler repo) and go to random.org 
- manually check if they have the green ring and then make a list of it. 
- check the google developer tools (fn F12 -> console) for error content message like content security policy prevented (like attached)
<img width="810" alt="Screenshot 2024-04-29 at 10 20 09 AM" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/155489035/984e5cbd-90fc-4ddd-a2ba-995de655bac8">

**Comment by katehausladen** [comment]
site list: https://github.com/privacy-tech-lab/gpc-web-crawler/blob/main/selenium-optmeowt-crawler/full-crawl-set.csv

**Comment by franciscawijaya** [comment]
This checklist is for both Chrome and Firefox: 
Notes: 
- Unless specifically stated, the extension had the same effect on both browsers for all websites. 
- Some websites could not be reached. I manually searched up the website (eg. incontrol clothing) but there are some websites that could not be reached and I could not find the new updated site name 
- Only one site that has no green ring (yourdictionary) but this site has a green ring on Firefox 

- [x] https://kimgarst.com/ 
- [x] https://tarvalon.net
- [x] https://uppermichiganssource.com
- [x] https://musterlive.aggienetwork.com
- [x] https://ama.org
- [x] https://nesn.com
- [x] https://godtube.com
- [x] https://vizio.com
- [x] https://cafilm.org
- [x] https://incontrolclothing.com/ (changed site name to https://www.incontrolclothing.com/)
- [x] https://zenefits.com/ (redirected to https://www.trinet.com/)
- [x] https://eloquii.com
- [x] https://canon.com/ (redirected to a page that state "site took too long to respond" — I manually went to the search bar and look up ‘canon’ which sent me to https://www.usa.canon.com/ ) (complete green)
- [x] https://boston.com
- [x] https://ranker.com/ (complete green)
- [x] https://socialworkdegreeguide.com
- [x] https://caring.com
- [x] https://sagaftra.org
- [x] https://bodyartforms.com
- [x] https://sacred-texts.com
- [x] https://submittable.com
- [x] https://marketplace.ivanti.com
- [x] https://assurancewireless.com
- [x] https://gunnar.com
- [x] https://neurostar.com
- [x] https://highdefdigest.com
- [x] https://brand24.com
- [x] https://belvederebanquets.com
- [x] https://forexfactory.com
- [x] https://bestbooks.multcolib.org/ (redirected to https://bestbooks.multcolib.org/#view=covers&year=2023)
- [x] https://coreseries-tape-selection-app.averydennison.com
- [x] https://msccruisesusa.com
- [x] https://elsevierhealth.com/ (site changed name to https://www.us.elsevierhealth.com/)
- [x] https://texomashomepage.com
- [ ] https://lordandtaylor.com/ (site can’t be reached) 
- [x] https://charactercounts.org
- [x] https://shiekh.com
- [x] https://dunkindonuts.com
- [x] https://timesunion.com
- [x] https://svahausa.com
- [x] https://careers.stelizabeth.com/ (takes a while before the green ring is on in chrome — normal on Firefox)
- [x] https://espn.com
- [x] https://velcro.com
- [x] https://sprite.com
- [x] https://mongabay.com
- [x] https://bamboohr.com
- [x] https://swnewsmedia.com
- [x] https://rs-stripe.mycbs4.com
- [x] https://strathmore.org
- [x] https://makershed.com
- [x] https://redrocknews.com
- [x] https://mediavine.com
- [x] https://wonderopolis.org
- [x] https://worldlabel.com
- [x] https://rpg.net
- [x] https://l-r-g.com
- [x] https://belk.com
- [x] https://genealogybank.com
- [x] https://natrol.com
- [ ] https://apoc.varian.com/ (resource not found) 
- [x] https://greencarreports.com
- [x] https://childrens.com/ (takes a while to load the green ring on Chrome — normal on Firefox)
- [x] https://learning.rcan.org
- [x] https://careerarc.com
- [x] https://bryant.sidearmstats.com/ 
- [x] https://verilymag.com
- [x] https://vendingworld.com
- [x] https://airliftcompany.com
- [x] https://frostriver.com
- [x] https://starwars.com
- [x] https://scrapbook.com
- [x] https://store.gardengatemagazine.com
- [ ] https://lyncdiscover.irmi.com/ (site can’t be reached)
- [x] https://sacnas.org
- [x] https://guide.farmigo.com/ 
- [x] https://hopecu.org
- [x] https://redandblack.com
- [x] https://greenvillelibrary.org
- [x] https://renewedvision.com
- [x] https://overdrive.daytonmetrolibrary.org
- [x] https://airforce.com
- [x] https://kjct8.com
- [x] https://ipm.auhsd.us
- [ ] https://yourdictionary.com/ (no green ring on Chrome but there is green ring on Firefox)
- [x] https://everestbands.com
- [x] https://cameraprive.com
- [x] https://flyontario.com
- [x] https://news-press.com
- [x] https://iphonelife.com
- [x] https://sugarandcloth.com
- [x] https://etundra.com
- [x] https://wboy.com
- [x] https://quote.americancollectors.com
- [x] https://afw.com
- [x] https://safari.katyisd.org
- [x] https://overstock.com
- [x] https://981thehawk.com
- [x] https://shopusahockey.com
- [x] https://rexburgstandardjournal.com
- [x] https://insideclimatenews.org

**Comment by franciscawijaya** [comment]
Attached is the difference of the developer tools' console for Chrom and Firefox for specifically yourdictionary.com 
<img width="1440" alt="Screenshot 2024-05-05 at 9 18 43 PM" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/155489035/b38131f7-0bd5-4e54-8bec-3107e7fa82d1">
<img width="1440" alt="Screenshot 2024-05-05 at 9 42 24 PM" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/155489035/ddbbcd2b-7036-47d4-81e2-239d9b8efb19">

**Comment by SebastianZimmeck** [comment]
Thanks, @franciscawijaya. 

> pick 100 random sites from the sample (in the crawler repo) and go to random.org

Well, random.org was for selecting the 100 random sites. :)

>  I manually searched up the website (eg. incontrol clothing) 

What do you mean by "incontrol clothing"?

Which version of OptMeowt did you use? The problem does not seem to be with the current version in the stores but with @OliverWang13's and @Mattm27's mv3 version ([branch 350-1](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/issue-350-1) or [branch 350-2](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/issue-350-2); @OliverWang13 and @Mattm27, which branch should be used actually?).

**Comment by franciscawijaya** [comment]
> What do you mean by "incontrol clothing"?

Some sites changed their name so I just manually searched the updated name 

> * https://incontrolclothing.com/ (changed site name to https://www.incontrolclothing.com/)

> Which version of OptMeowt did you use? The problem does not seem to be with the current version in the stores but with @OliverWang13's and @Mattm27's mv3 version ([branch 350-1](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/issue-350-1) or [branch 350-2](https://github.com/privacy-tech-lab/gpc-optmeowt/tree/issue-350-2); @OliverWang13 and @Mattm27, which branch should be used actually?).

I loaded unpacked extension for version 4.3.1. I think I used branch 350-1.

**Comment by SebastianZimmeck** [comment]
| URL | Chrome | Firefox |
| --- | --- | ---| 
| url | ✅ | blah | 

(Just a sample to modify)

@franciscawijaya will check again using branch 350-5.

**Comment by franciscawijaya** [comment]
Check if that version would work for a good percentage of sites. If not, contact Oliver & Matt.

**Comment by SebastianZimmeck** [comment]
@franciscawijaya, to get the most recent versions, you can do:

For Firefox: `git checkout issue-350-5`.

For Chrome: `git checkout 13c0f830011ef9ed72dddf16b16b3e533b7abae7` (the currently latest commit reference).

Then, you can check with `git status` that you are on those branches and, if so, follow the [normal setup procedure](https://github.com/privacy-tech-lab/gpc-optmeowt?tab=readme-ov-file#4-installing-optmeowt-from-source).

**Comment by franciscawijaya** [comment]
**URL | Chrome | Firefox**
-- | -- | --
https://bdcnetwork.com  | ✅ |  ✅ | 
-- | -- | --
https://gazelle.com  | ✅ |  ✅ | 
-- | -- | --
https://thredup.com  | ✅ |  ✅ | 
-- | -- | --
https://toasttab.com  | ✅ |  ✅ | 
-- | -- | --
https://thedelite.com  | ✅ |  ✅ | 
-- | -- | --
https://nwaonline.com  | ✅  | ✅ | 
-- | -- | --
https://vivint.com  | ✅  | ✅ | 
-- | -- | --
https://vineyardvines.com  | ✅  | ✅ | 
-- | -- | --
https://inboxdollars.com  | ✅  | ✅ | 
-- | -- | --
https://genealogy.com  | ✅  | ✅ | 
-- | -- | --
https://techlicious.com  | ✅  | ✅ | 
-- | -- | --
https://big12sports.com  | ✅  | ✅ | 
-- | -- | --
https://metro-magazine.com  | ✅  | ✅ | 
-- | -- | --
https://kalashnikov-usa.com  | ✅  | ✅ | 
-- | -- | --
https://facetory.com  | ✅  | ✅ | 
-- | -- | --
https://wwbw.com  | ✅  | ✅ | 
-- | -- | --
https://shopversona.com| ✅  | ✅ | 
-- | -- | --
https://peacecenter.org  | ✅  | ✅ | 
-- | -- | --
https://atcc.org  | ✅  | ✅ | 
-- | -- | --
https://commercebank.com  | ✅  | ✅ | 
-- | -- | --
https://blog.educreations.com  | ✅  | ✅ | 
-- | -- | --
https://chaosium.com  | ✅  | ✅ | 
-- | -- | --
https://openvpn.net  | ✅  | ✅ | 
-- | -- | --
https://josbank.com  | ✅   | ✅ | 
-- | -- | --
https://granicus.com  | ✅  | ✅ | 
-- | -- | --
https://niketalk.com  | ✅  | ✅ | 
-- | -- | --
https://zurichna.com  | ✅  | ✅ | 
-- | -- | --
https://sacred-texts.com  | ✅  | ✅ | 
-- | -- | --
https://postermywall.com  | ✅  | ✅ | 
-- | -- | --
https://galactictoys.com  | ✅  | ✅ | 
-- | -- | --
https://rubytuesday.com  | ✅  | ✅ | 
-- | -- | --
https://postscanmail.com  | ✅  | ✅ | 
-- | -- | --
https://viewsonic.com  | ✅  | ✅ | 
-- | -- | --
https://kivitv.com  | ✅  | ✅ | 
-- | -- | --
https://everaccountable.com  | ✅  | ✅ | 
-- | -- | --
https://alltribes.com  | ✅  | ✅ | 
-- | -- | --
https://fredmeyer.com  | ✅  | ✅ | 
-- | -- | --
https://myfwc.com  | ✅  | ✅ | 
-- | -- | --
https://icq.com  | ✅  | ✅ | 
-- | -- | --
https://autodiscover.patientslikeme.com  | ✅  | ✅ | 
-- | -- | --
https://azdailysun.com  | ✅  | ✅ | 
-- | -- | --
https://betterhelp.com  | ✅  | ✅ | 
-- | -- | --
https://elitetraveler.com  | ✅  | ✅ | 
-- | -- | --
https://minitab.com  | ✅  | ✅ | 
-- | -- | --
https://cbs19news.com  | ✅  | ✅ | 
-- | -- | --
https://powernationtv.com  | ✅  | ✅ | 
-- | -- | --
https://thetrumpet.com  | ✅  | ✅ | 
-- | -- | --
https://gointothestory.blcklst.com  | ✅  | ✅ | 
-- | -- | --
https://unboundmedicine.com  | ✅  | ✅ | 
-- | -- | --
https://redwoodcu.org  | ✅  | ✅ | 
-- | -- | --
https://ritathletics.com  | ✅  | ✅ | 
-- | -- | --
https://donatelife.net  | ✅  | ✅ | 
-- | -- | -- 
https://merck.com  | ✅  | ✅ | 
-- | -- | --
https://schneider.com  | ✅  | ✅ | 
-- | -- | --
https://members.nysba.org  | ✅  | ✅ | 
-- | -- | --
https://ellaclaireinspired.com  | ✅  | ✅ | 
-- | -- | --
https://nexternal.com  | ✅  | ✅ | 
-- | -- | --
https://evo.com  | ✅  | ✅ | 
-- | -- | --
https://speedify.com  | ✅  | ✅ | 
-- | -- | --
https://neilpatel.com  | ✅  | ✅ | 
-- | -- | --
https://signal.org  | ✅  | ✅ | 
-- | -- | --
https://intrustbank.com  | ✅  | ✅ | 
-- | -- | --
https://dailybulletin.com | ✅  | ✅ | 
-- | -- | --
https://boingboing.net  | ✅  | ✅ | 
-- | -- | --
https://megapath.com  | ✅  | ✅ | 
-- | -- | --
https://revinate.com  | ✅  | ✅ | 
-- | -- | --
https://biblestudytools.com  | ✅  | ✅ | 
-- | -- | --
https://membership.aaep.org  | ✅  | ✅ | 
-- | -- | --
https://rosebowlstadium.com  | ✅  | ✅ | 
-- | -- | --
https://staterbros.com  | ✅  | ✅ | 
-- | -- | --
https://usedvending.com  | ✅  | ✅ | 
-- | -- | --
https://joovv.com  | ✅  | ✅ | 
-- | -- | -- 
https://imagequix.com  | ✅  | ✅ | 
-- | -- | --
https://mylocker.net  | ✅  | ✅ | 
-- | -- | --
https://quickcountry.com  | ✅  | ✅ | 
-- | -- | --
https://visitidaho.org  | ✅  | ✅ | 
-- | -- | --
https://hbcugameday.com | ✅  | ✅ | 
-- | -- | --
https://cupertino.org  | ✅  | ✅ | 
-- | -- | --
https://nissinfoods.com  | ✅  | ✅ | 
-- | -- | --
https://lww.com  | ✅  | ✅ | 
-- | -- | -- 
https://enchroma.com | ✅  | ✅ | 
-- | -- | --
https://multitracks.com | ✅  | ✅ | 
-- | -- | --
https://phs.org | ✅  | ✅ | 
-- | -- | --
https://directory.sway.com  | ✅  | ✅ | 
-- | -- | --
https://lillypulitzer.com  | ✅  | ✅ | 
-- | -- | --
https://gcfglobal.org  | ✅  | ✅ | 
-- | -- | --
https://ria.com  | ✅  | ✅ | 
-- | -- | --
https://crackle.com | ✅  | ✅ | 
-- | -- | --
https://pledge.com | ✅  | ✅ | 
-- | -- | --
https://synchronyfinancial.com | ✅  | ✅ | 
-- | -- | --
https://impacthub.net | ✅  | ✅ | 
-- | -- | --
https://dickinson-wright.com | ✅  | ✅ | 
-- | -- | -- 
https://sumerianrecords.com | ✅  | ✅ | 
-- | -- | --
https://inrix.com| ✅  | ✅ | 
-- | -- | --
https://lifeandscience.org | ✅  | ✅ | 
-- | -- | --
https://chatsworth.com | ✅  | ✅ | 
-- | -- | --
https://store.chatwork.com | ✅  | ✅ | 
-- | -- | --
https://genstattu.com | ✅  | ✅ | 
-- | -- | --
https://alzheimersnewstoday.com | ✅  | ✅ | 
-- | -- | --
https://foodbankheartland.org | ✅  | ✅ | 

All sample sites have green ring! Github on Firefox has green ring; only github on Chrome does not.

**Comment by SebastianZimmeck** [comment]
Great! Feel free to close any issue once it is done, @franciscawijaya.

**Comment by SebastianZimmeck** [comment]
Reopening. Seems v5.0.0 does not have the green ring and is also not sending the GPC signal properly.

**Comment by franciscawijaya** [comment]
<img width="1440" alt="Screenshot 2024-05-23 at 8 46 26 PM" src="https://github.com/privacy-tech-lab/gpc-optmeowt/assets/155489035/06464d5e-0e54-4dcd-a79c-50b98fadcb2a">

According to the browser developer tools, there currently is an xml parsing error. Potentially concerning the xml syntax in the new updated version? 

It is also worth to note that the "cookie-test" being rejected for invalid domain; though, this could maybe come from the underlying xml parsing error.

**Comment by franciscawijaya** [comment]
the xml parsing error seems to be from from Permutive so that actually does not have any correlation with the extension.

**Comment by SebastianZimmeck** [comment]
As @Mattm27 found, the issue after re-opening was related to the dist manifests being outdated; only the dev manifests were updated after the switch to mv3. [v5.0.1](https://github.com/privacy-tech-lab/gpc-optmeowt/releases/tag/v5.0.1) fixes this bug.
