### ISSUE TITLE
Update package.json to solve Dependabot alert

### ISSUE THREAD

**Issue by Mattm27** [privacy-tech-lab/gpc-optmeowt#467]
From what it looks like we just need to update our dependencies and add a resolutions field, but opening this issue in case it turns out to be more than that.

**Comment by SebastianZimmeck** [comment]
Sounds good!

(cc'ing @atlasharry)

**Comment by SebastianZimmeck** [comment]
[Corresponding Privacy Pioneer issue](https://github.com/privacy-tech-lab/privacy-pioneer/issues/579) for reference.
