### ISSUE TITLE
Update DAA cookie list

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#73]
As the [DAA Opt Out Tool](https://optout.privacyrights.info/?c=1) may change its cookies from time to time, we have to update the DAA cookie list on our end as well.

(cc'ing @asalia-1)

**Comment by SebastianZimmeck** [comment]
We will update the cookie list from time to time, possibly, the next time in a few months as part of our paper publication.

**Comment by SebastianZimmeck** [comment]
Some time in February 2021 may be enough.

**Comment by SebastianZimmeck** [comment]
I am reopening this issue as some time has passed. We should check and update, if necessary, the DAA cookies (not sure if there are other cookies we need to update as well).

**Comment by SebastianZimmeck** [comment]
These cookie names and values are in the data folder in .json files. The way to do this is to go to the following site

https://optout.privacyrights.info/?c=1

and on a fresh browser check which cookies are set and identify the opt out cookies.

**Comment by OliverWang13** [comment]
I am working through the list and updating the cookies. However, a few sites displayed "opt out temporarily unavailable." These 23 sites may need to be reverified if they are ever working again. Below is a list of these sites.

- 33Across
- AddThis
- Amobee
- Apollo Program
- Choozle
- Connexity
- Criteo
- Datonics
- Dstillery
- EMX
- Extreme Reach
- Eyeota
- Flashtalking
- Index Exchange
- IQM.com
- LiveIntent
- Latome
- Neustar/Aggregate Knowledge
- Oracle Data Cloud
- Pulpo
- Unruly Group LLC.
- Verizon Media
- Zeta Global

**Comment by SebastianZimmeck** [comment]
@OliverWang13, do you know what "opt out temporarily unavailable" means? Is this message displayed in the DAA opt out tool? Are those companies no longer DAA members, this is a technical glitch, ...?  

Do you have screenshot?

**Comment by OliverWang13** [comment]
This is what I am seeing after running "Opt Out All". I am not sure what "opt out temporarily unavailable" means.

![Screen Shot 2022-05-18 at 1 54 12 PM](https://user-images.githubusercontent.com/82842273/169109758-7aa558d9-e314-4455-b73e-eb3d603e144c.png)

**Comment by SebastianZimmeck** [comment]
I am not sure either. Could you try to go directly to the ad networks' sites and check if they have an opt out functionality there, use that, and see what the cookie name/value is?

Are they maybe participating in a different industry organization? Maybe, Network Advertising Inititative (NAI), others ...?

Also, check their privacy policies, how does one opt out? Maybe, you can find something there.

Try another browser, disabling any extensions that may block the tool?

**Comment by OliverWang13** [comment]
I tried firefox and even less sites were able to opt out. I can check some of the privacy policies and see if they mention another possible organization. I can try to opt out if they have a "do not sell my personal information" link and check the cookies after.

**Comment by SebastianZimmeck** [comment]
> I can try to opt out if they have a "do not sell my personal information" link and check the cookies after.

Yes, maybe, they also have a generic opt out cookie (opt out from tracking or the like as opposed to specific Do Not Sell). Whatever they have, we can just include.

**Comment by SebastianZimmeck** [comment]
> I tried firefox and even less sites were able to opt out.

By default, Firefox is block much more. You can try Chrome and enable everything in the setting, i.e., least privacy-sensitive settings (allow all cookies, all JS, fingerprinting, etc.).

**Comment by OliverWang13** [comment]
Using `33across.com` as an example, their privacy policy mentions DAA and NAI, and they provide their own method for opting out. After hitting their button to opt-out the proper cookie shows up, so I should be able to act similarly on other sites that the opt-out was unsuccessful for. Would we ever consider treating NAI sites like DAA sites? Should I be recording those notable cookies too?

**Comment by SebastianZimmeck** [comment]
> Would we ever consider treating NAI sites like DAA sites? Should I be recording those notable cookies too?

Yes to both.

We should also update the readme, code comments, and wherever we document that we include custom cookies and NAI cookies.

**Comment by SebastianZimmeck** [comment]
@OliverWang13, when you open the PR, please add me as a reviewer.

**Comment by OliverWang13** [comment]
What about sites that participate in DAA's WebChoices tool? Should we copy down the cookie information for them as well?

**Comment by SebastianZimmeck** [comment]
Can you provide the link to that one (as well as all other tools that you came about)?

**Comment by OliverWang13** [comment]
https://optout.networkadvertising.org/?c=1
https://optout.privacyrights.info/?c=1
https://optout.aboutads.info/?c=2&lang=EN

**Comment by SebastianZimmeck** [comment]
Which is the one that we are currently doing? Is it just https://digitaladvertisingalliance.org/integrate-webchoices-ccpa or anything else?

Also, [this](https://github.com/privacy-tech-lab/gpc-optmeowt/blob/main/src/data/cookiesDAA.js) is the only file you are working with, right? Or do we have other files with cookie names and values (except for the usprivacy cookie)?  If that remains the only file, we should rename it to just cookies.js as it goes beyond DAA cookies. At least, there is one custom cookie, the [FullStory cookie](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/269), that you include there, right?

**Comment by OliverWang13** [comment]
Currently, our `cookiesDAA.js` file is based on `https://optout.privacyrights.info/?c=1`. I can rename it and add the other cookies as well.

**Comment by OliverWang13** [comment]
Ok, that sounds good. Should we still rename the file or should we keep it `cookiesDAA.js`?

**Comment by SebastianZimmeck** [comment]
Let's rename if you include at least one other cookie (you include FullStory there, for example, right?).

**Comment by OliverWang13** [comment]
The site `choozle.com` is listed on the CCPA Opt-Out Tool, but looking at its Privacy Policy, it says the only way to give a CCPA request is to send an email to their privacy contact. So their presence on the Opt-Out tool might be outdated, and I am not sure if I should explore any other non-CCPA opt-out options.

**Comment by OliverWang13** [comment]
For the site `pulpomedia.com`, it seems like it does not exist anymore, so there might not be any point in including cookies for them.

**Comment by SebastianZimmeck** [comment]
Sounds good!

**Comment by SebastianZimmeck** [comment]
One point we should test here is that our extension does not lag or crash upon first install. The reason is that upon first install we iterate over the cookies and place those in the browser storage.

**Comment by OliverWang13** [comment]
I just pushed the updated DAA cookies and renamed the file to this issue. I was able to find an opt-out cookie for every site on the list except for `unruly.co`, I believe. They have an opt-out button that takes you to a page where you enter your email and it can delete your data, which seems outside the scope of our extension.

**Comment by OliverWang13** [comment]
I have tested the new code and everything compiles fine without crashing, so I will open a pull request to main.
